Repository neo4j/neo4j-documentation, pull requests merged in 2018-12, with the labels that each got.

#283 Update Spatial to have toInteger instead of toInt
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
Labels: 3.4, bug, cypher

#284 Remove or update tests or examples that were using legacy indexes.
  contents/pom.xml
  cypher/cypher-docs/src/main/java/org/neo4j/procedure/example/IndexingProcedure.java
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  embedded-examples/src/main/java/org/neo4j/examples/CalculateShortestPath.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithIndexing.java
  embedded-examples/src/main/java/org/neo4j/examples/socnet/PersonRepository.java
  embedded-examples/src/test/java/org/neo4j/examples/EmbeddedNeo4jWithIndexingDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/GetOrCreateDocIT.java
  embedded-examples/src/test/java/org/neo4j/examples/socnet/SocnetTest.java
  lucene/src/test/java/examples/ImdbDocTest.java
  lucene/src/test/java/org/neo4j/index/impl/lucene/explicit/AbstractLuceneIndexTest.java
  lucene/src/test/java/org/neo4j/index/impl/lucene/explicit/TestLuceneIndex.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/GetOnRootDocIT.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/FunctionalTestHelper.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/ServerHelper.java
  server-test-utils/src/main/java/org/neo4j/doc/server/rest/domain/GraphDbHelper.java
  test-framework-enterprise/src/main/java/org/neo4j/doc/test/TestEnterpriseGraphDatabaseFactory.java
  test-framework/src/main/java/org/neo4j/doc/test/DbRepresentation.java
  test-framework/src/main/java/org/neo4j/doc/test/GraphDescription.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/DatabaseRule.java
Labels: 4.0

#281 Describe limitations of composite indexes better
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/schema-index/fulltext-schema-index.adoc
  cypher/cypher-docs/src/docs/dev/ql/schema-index/index.asciidoc
  cypher/cypher-docs/src/docs/dev/schema.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: 3.5, cypher

#288 Adapt docs code to neo4j clean-ups
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/DocumentingTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
Labels: 4.0, cypher

#289 Update harness to be commercial harness and use new commercial harness artifact.
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/ExtensionTestingDocIT.java
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/JUnitDocIT.java
Labels: 4.0

#290 Use new commercial test artifact
  contents/pom.xml
Labels: 4.0

#291 Quick fix of failing JMX bean counter test
  jmx/src/test/java/org/neo4j/doc/jmx/CausalClusterJmxDocsTest.java
Labels: 4.0
