Repository neo4j/neo4j-documentation, pull requests merged in 2018-10, with the labels that each got.

#268 Remove neo4j-shell
  config-docs/pom.xml
  contents/pom.xml
  contents/src/tools/index.asciidoc
  embedded-examples/README.txt
  embedded-examples/pom.xml
  embedded-examples/src/main/java/org/neo4j/examples/Neo4jShell.java
  pom.xml
  shell/pom.xml
  shell/src/docs/dev/shell.asciidoc
  shell/src/test/java/org/neo4j/shell/Documenter.java
  shell/src/test/java/org/neo4j/shell/ShellDocTest.java
  shell/src/test/resources/autoindex.properties
Labels: 3.5

#263 Add Cypher deprecations
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
  cypher/cypher-docs/src/docs/dev/tutorials/gists/cypher/finding-paths.asciidoc
  cypher/cypher-docs/src/docs/graphgists/intro/data-structures.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListFunctionsTest.scala
Labels: 3.5, cypher

#264 Prettify lines with line breaks
  cypher/cypher-docs/pom.xml
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalDurationFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/DocBuilder.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/Document.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/DocumentingTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/ContentAndResultMergerTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/DocumentTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/QueryResultContentBuilderTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/QueryRunnerTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/RestartableDatabaseTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/RunnableContentTest.scala
  cypher/cypher-prettifier/pom.xml
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/Prettifier.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/ParserTestBase.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
  cypher/graphgist/pom.xml
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/State.java
  cypher/pom.xml
  cypher/refcard-tests/pom.xml
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  embedded-examples/pom.xml
  embedded-examples/src/test/java/org/neo4j/examples/AbstractJavaDocTestBase.java
  server-test-utils/pom.xml
  server-test-utils/src/main/java/org/neo4j/doc/server/rest/AbstractRestFunctionalTestBase.java
Labels: 3.5

#272 Fixes to metrics output
  metrics-docs/pom.xml
Labels: 3.1, Dependencies w. other PR

#270 Add information about quoting in csv format
  cypher/cypher-docs/src/docs/dev/ql/load-csv/csv-file-format.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CsvFile.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 3.1, cypher

#273 Fix iBob docs
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: 3.5, cypher

#278 Fix compilation error.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
Labels: 3.5, Dependencies w. other PR
