Repository neo4j/neo4j-documentation, pull requests merged in 2018-09, with the labels that each got.

#252 3.5 index backed order by
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
Labels: 3.5, cypher

#251 IN operator cleanups
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 3.5, cypher

#257 Update edition package
  backup/src/test/java/org/neo4j/doc/backup/TestBackup.java
  test-framework/src/main/java/org/neo4j/doc/test/ImpermanentGraphDatabase.java
  test-framework/src/main/java/org/neo4j/doc/test/TestGraphDatabaseFactory.java
Labels: 3.0

#259 Editions update
  test-framework/src/main/java/org/neo4j/doc/test/TestGraphDatabaseFactory.java
Labels: 3.5

#260 Update from server:
  jmx/src/test/java/org/neo4j/doc/jmx/CausalClusterJmxDocsTest.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityServerBuilder.java
Labels: 3.5

#256 Add documentation on how to use the fulltext schema indexes.
  cypher/cypher-docs/src/docs/dev/ql/schema-index/explicit-index-procedures.adoc
  cypher/cypher-docs/src/docs/dev/ql/schema-index/fulltext-schema-index.adoc
  cypher/cypher-docs/src/docs/dev/ql/schema-index/index.asciidoc
  cypher/cypher-docs/src/docs/dev/schema.asciidoc
Labels: 3.5, Dependencies w. other PR

#265 Cleanup ThirdPartyFileSystem leftovers.
  test-framework/src/main/java/org/neo4j/doc/test/rule/fs/FileSystemRule.java
  test-framework/src/main/java/org/neo4j/graphdb/mockfs/DelegatingFileSystemAbstraction.java
  test-framework/src/main/java/org/neo4j/graphdb/mockfs/EphemeralFileSystemAbstraction.java
Labels: 3.5
