Repository neo4j/neo4j-documentation, pull requests merged in 2019-01, with the labels that each got.

#286 Force bolt connector settings to be recognized
  config-docs/src/main/java/org/neo4j/doc/ConfigDocsGenerator.java
Labels: 3.5

#292 Update metrics docs generator.
  metrics-docs/pom.xml
  metrics-docs/src/main/java/org/neo4j/metrics/docs/MetricsAsciiDocGenerator.java
Labels: 4.0

#293 Use commercial server artifacts
  config-docs/pom.xml
  jmx/pom.xml
  jmx/src/test/java/org/neo4j/doc/jmx/CausalClusterJmxDocsTest.java
Labels: 4.0

#298 Adapt to product extensions rename.
  test-framework/src/main/java/org/neo4j/doc/test/ImpermanentGraphDatabase.java
  test-framework/src/main/java/org/neo4j/doc/test/TestGraphDatabaseFactory.java
Labels: 4.0

#300 Rename CausalClusteringSettings path
  config-docs/pom.xml
Labels: 4.0, bug

#301 Adapt tests to new harness rules
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/ExtensionTestingDocIT.java
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/JUnitDocIT.java
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/ExtensionTestingDocIT.java
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/JUnitDocIT.java
  server-examples/src/test/java/org/neo4j/examples/server/unmanaged/UnmanagedExtensionsDocIT.java
Labels: 4.0

#299 Remove DatabaseRule.createNodeId.
  test-framework/src/main/java/org/neo4j/doc/test/rule/DatabaseRule.java
Labels: 4.0, Dependencies w. other PR, kernel

#303 Use new Dependency resolve import.
  test-framework/src/main/java/org/neo4j/doc/test/rule/DatabaseRule.java
Labels: 4.0

#305 Adapt to product procedures changes.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
Labels: 4.0

#306 Use new global module instead of platform module.
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityServerBuilder.java
  test-framework-enterprise/src/main/java/org/neo4j/doc/test/TestEnterpriseGraphDatabaseFactory.java
  test-framework/src/main/java/org/neo4j/doc/test/ImpermanentGraphDatabase.java
  test-framework/src/main/java/org/neo4j/doc/test/TestGraphDatabaseFactory.java
Labels: 4.0
