Repository neo4j/neo4j-documentation, pull requests merged in 2019-05, with the labels that each got.

#339 Adapt to product facade changes.
  test-framework/src/main/java/org/neo4j/doc/test/TestDatabaseManagementServiceBuilder.java
Labels: 4.0

#341 Add database name method.
  test-framework/src/main/java/org/neo4j/doc/test/rule/DatabaseRule.java
Labels: 4.0

#342 Cleanup jmx tests
  embedded-examples/src/test/java/org/neo4j/examples/JmxDocTest.java
  jmx/src/test/java/org/neo4j/doc/jmx/CausalClusterJmxDocsTest.java
Labels: 4.0

#343 Adapt docs to product changes around EnterpriseCompilerFactory
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ExecutionEngineFactory.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/QueryResultContentBuilderTest.scala
Labels: 4.0, cypher

#340 Update description of scalar unwind
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnwindTest.scala
Labels: 4.0, cypher

#349 Use new dbms api package.
  cypher/cypher-docs/src/main/java/org/neo4j/cypher/example/JavaQuery.java
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/IntroDocTest.java
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ExecutionEngineFactory.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/QueryResultContentBuilderTest.scala
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/CypherDoc.java
  cypher/graphgist/src/test/java/org/neo4j/doc/cypherdoc/BlockTypeTest.java
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  embedded-examples/src/main/java/org/neo4j/examples/CalculateShortestPath.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithBolt.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithCustomLogging.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithSLF4JLogging.java
  embedded-examples/src/main/java/org/neo4j/examples/NewMatrix.java
  embedded-examples/src/main/java/org/neo4j/examples/TerminateTransactions.java
  embedded-examples/src/main/java/org/neo4j/examples/TraversalExample.java
  embedded-examples/src/main/java/org/neo4j/examples/orderedpath/OrderedPath.java
  embedded-examples/src/test/java/org/neo4j/doc/metatest/TestJavaTestDocsGenerator.java
  embedded-examples/src/test/java/org/neo4j/examples/AbstractJavaDocTestBase.java
  embedded-examples/src/test/java/org/neo4j/examples/Neo4jBasicDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/ProcedureExampleDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/ReadOnlyDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/StartWithConfigurationDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/orderedpath/OrderedPathDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/socnet/SocnetTest.java
  graphviz/src/main/java/org/neo4j/visualization/graphviz/Script.java
  import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java
  kernel/src/test/java/examples/BatchInsertDocTest.java
  lucene/src/test/java/org/neo4j/index/impl/lucene/explicit/AbstractLuceneIndexTest.java
  procedures/src/main/java/org/neo4j/doc/Neo4jInstance.java
  procedures/src/main/java/org/neo4j/doc/ProcedureReferenceGenerator.java
  test-framework/src/main/java/org/neo4j/doc/test/DbRepresentation.java
  test-framework/src/main/java/org/neo4j/doc/test/TestDatabaseManagementServiceBuilder.java
  test-framework/src/main/java/org/neo4j/doc/test/index/Neo4jTestCase.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/DatabaseRule.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/EmbeddedDatabaseRule.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/ImpermanentDatabaseRule.java
Labels: 4.0

#351 4.0 start of cleaning
  cypher/pom.xml
  doctools/pom.xml
  graphviz/pom.xml
  import-tool/pom.xml
  import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java
  jmx/pom.xml
  kernel/pom.xml
  kernel/src/test/java/examples/DeadlockDocTest.java
  lucene/pom.xml
  lucene/src/test/java/org/neo4j/index/impl/lucene/explicit/AbstractLuceneIndexTest.java
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-test/pom.xml
  pom.xml
  server-test-utils/pom.xml
  test-framework/pom.xml
Labels: 4.0

#352 Remove custom test commercial database factory.
  contents/pom.xml
  contents/src/advanced/index.asciidoc
  cypher/cypher-docs/pom.xml
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ExecutionEngineFactory.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/RestartableDatabaseTest.scala
  cypher/graphgist/pom.xml
  cypher/refcard-tests/pom.xml
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  pom.xml
  test-framework-enterprise/pom.xml
  test-framework-enterprise/src/main/java/org/neo4j/doc/test/TestEnterpriseGraphDatabaseFactory.java
Labels: 4.0, kernel

#353 Cleanup custom docs test database factories.
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/IntroDocTest.java
  cypher/graphgist/pom.xml
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/CypherDoc.java
  cypher/graphgist/src/test/java/org/neo4j/doc/cypherdoc/BlockTypeTest.java
  embedded-examples/pom.xml
  embedded-examples/src/test/java/org/neo4j/doc/metatest/TestJavaTestDocsGenerator.java
  embedded-examples/src/test/java/org/neo4j/examples/AbstractJavaDocTestBase.java
  embedded-examples/src/test/java/org/neo4j/examples/AclExampleDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/DocumentationDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/GetOrCreateDocIT.java
  embedded-examples/src/test/java/org/neo4j/examples/ImpermanentGraphJavaDocTestBase.java
  embedded-examples/src/test/java/org/neo4j/examples/Neo4jBasicDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/PathFindingDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/ProcedureExampleDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/Roles.java
  embedded-examples/src/test/java/org/neo4j/examples/RolesDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/TraversalDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/UniquenessOfPathsDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/orderedpath/OrderedPathDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/socnet/SocnetTest.java
  graphviz/src/test/java/org/neo4j/visualization/graphviz/TestGraphvizSubgraphOutput.java
  graphviz/src/test/java/org/neo4j/visualization/graphviz/TestNewGraphvizWriter.java
  kernel/src/test/java/examples/BatchInsertDocTest.java
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/JUnitDocIT.java
  pom.xml
  server-docs/src/test/java/org/neo4j/doc/server/ExclusiveServerTestBase.java
  server-test-utils/src/main/java/org/neo4j/doc/server/SharedServerTestBase.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityServerBuilder.java
  test-framework/src/main/java/org/neo4j/doc/test/DbRepresentation.java
  test-framework/src/main/java/org/neo4j/doc/test/TestDatabaseManagementServiceBuilder.java
  test-framework/src/main/java/org/neo4j/doc/test/impl/ChannelInputStream.java
  test-framework/src/main/java/org/neo4j/doc/test/impl/ChannelOutputStream.java
  test-framework/src/main/java/org/neo4j/doc/test/index/Neo4jTestCase.java
  test-framework/src/main/java/org/neo4j/doc/test/mockito/matcher/Neo4jMatchers.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/DatabaseRule.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/EmbeddedDatabaseRule.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/ExternalResource.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/ImpermanentDatabaseRule.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/RetryHandler.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/SuppressOutput.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/fs/DefaultFileSystemRule.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/fs/EphemeralFileSystemRule.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/fs/FileSystemRule.java
  test-framework/src/main/java/org/neo4j/graphdb/mockfs/DelegatingFileSystemAbstraction.java
  test-framework/src/main/java/org/neo4j/graphdb/mockfs/EphemeralFileSystemAbstraction.java
  test-framework/src/main/java/org/neo4j/graphdb/mockfs/UncloseableDelegatingFileSystemAbstraction.java
Labels: 4.0

#354 Remove test directory rule usage
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MapsTest.scala
  doctools/pom.xml
  doctools/src/test/java/org/neo4j/doc/metatest/AsciiDocGeneratorTest.java
  embedded-examples/src/test/java/org/neo4j/doc/metatest/TestJavaTestDocsGenerator.java
  embedded-examples/src/test/java/org/neo4j/examples/Neo4jBasicDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/StartWithConfigurationDocTest.java
  server-docs/src/test/java/org/neo4j/doc/server/ExclusiveServerTestBase.java
  server-docs/src/test/java/org/neo4j/doc/server/NeoServerJAXRSDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/SecurityRulesDocIT.java
  test-framework/src/main/java/org/neo4j/doc/test/rule/TestDirectory.java
Labels: 4.0
