Repository neo4j/neo4j-documentation, pull requests merged in 2019-06, with the labels that each got.

#350 Updated documentation for Composite indices
  cypher/cypher-docs/src/docs/dev/ql/schema-index/index.asciidoc
  cypher/cypher-docs/src/docs/dev/schema.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: 4.0, cypher

#356 Update annotations after corresponding product update.
  embedded-examples/src/test/java/org/neo4j/doc/metatest/TestJavaTestDocsGenerator.java
  embedded-examples/src/test/java/org/neo4j/examples/AclExampleDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/DocumentationDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/Roles.java
  embedded-examples/src/test/java/org/neo4j/examples/RolesDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/TraversalDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/UniquenessOfPathsDocTest.java
  metrics-docs/src/main/java/org/neo4j/metrics/docs/MetricsAsciiDocGenerator.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/AuthenticationDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/SecurityRulesDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/UsersDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/transactional/TransactionDocIT.java
  test-framework/src/main/java/org/neo4j/doc/test/TestData.java
Labels: 4.0

#355 Updates after internal refactoring
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/DocsExecutionResult.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/QueryResultContentBuilderTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
Labels: 4.0

#358 Add extra parameter to `getProperty`
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/internal/CypherSerializer.scala
Labels: 4.0, Dependencies w. other PR, cypher

#359 Fix compilation errors after product updates
  config-docs/pom.xml
  embedded-examples/pom.xml
  embedded-examples/src/main/java/org/neo4j/examples/socnet/Person.java
  embedded-examples/src/test/java/org/neo4j/examples/socnet/SocnetTest.java
  metrics-docs/pom.xml
  pom.xml
Labels: 4.0

#360 updated all fulltext to full-text
  cypher/cypher-docs/src/docs/dev/ql/schema-index/explicit-index-procedures.adoc
  cypher/cypher-docs/src/docs/dev/ql/schema-index/fulltext-schema-index.adoc
  cypher/cypher-docs/src/docs/dev/ql/schema-index/index.asciidoc
  cypher/cypher-docs/src/docs/dev/schema.asciidoc
  lucene/src/test/java/examples/ImdbDocTest.java
Labels: 3.5
