Repository neo4j/neo4j-documentation, pull requests merged in 2019-03, with the labels that each got.

#312 Removal of deprecated HTTP APIs:
  server-docs/src/test/java/org/neo4j/doc/server/BatchOperationHeaderDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/GetOnRootDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/AuthenticationDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/CommunityServerTestBase.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/SecurityRulesDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/UsersDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/transactional/TransactionDocIT.java
  server-examples/src/main/java/org/neo4j/examples/server/plugins/DepthTwo.java
  server-examples/src/main/java/org/neo4j/examples/server/plugins/GetAll.java
  server-examples/src/main/java/org/neo4j/examples/server/plugins/ShortestPath.java
  server-examples/src/main/resources/META-INF/services/org.neo4j.server.plugins.ServerPlugin
  server-examples/src/test/java/org/neo4j/examples/server/AbstractPluginTestBase.java
  server-examples/src/test/java/org/neo4j/examples/server/DepthTwoDocIT.java
  server-examples/src/test/java/org/neo4j/examples/server/GetAllDocIT.java
  server-examples/src/test/java/org/neo4j/examples/server/ShortestPathDocIT.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/FunctionalTestHelper.java
Labels: 4.0

#316 Fix procedures imports.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/CallTest.scala
Labels: 4.0

#317 Default db adaptations
  import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityServerBuilder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/ServerHelper.java
  test-framework/src/main/java/org/neo4j/doc/test/TestGraphDatabaseFactory.java
Labels: 4.0

#319 Community system db adaptations
  test-framework-enterprise/src/main/java/org/neo4j/doc/test/TestEnterpriseGraphDatabaseFactory.java
  test-framework/src/main/java/org/neo4j/doc/test/ImpermanentGraphDatabase.java
  test-framework/src/main/java/org/neo4j/doc/test/TestGraphDatabaseFactory.java
Labels: 4.0

#318 Fix imports after Neo4j refactoring
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ExecutionEngineFactory.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: 4.0, Dependencies w. other PR, cypher

#320 Bump source and target version to java 11. Fix test failures.
  config-docs/pom.xml
  metrics-docs/pom.xml
  pom.xml
  test-framework/src/main/java/org/neo4j/doc/test/ImpermanentGraphDatabase.java
Labels: 4.0

#323 Update checkstyle to 8.18
  pom.xml
Labels: 3.5

#326 Restructuring the user defined functions for improved symmetry
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/user-defined-functions.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UserDefinedAggregationFunctionTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UserDefinedFunctionTest.scala
Labels: 3.4, bug, cypher

#327 Remove UDC.
  config-docs/pom.xml
Labels: 4.0

#329 Update tests to respect mandatory tx logs
  import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java
  kernel/src/test/java/examples/BatchInsertDocTest.java
Labels: 4.0
