Repository neo4j/neo4j-documentation, pull requests merged in 2019-07, with the labels that each got.

#363 Fix doc tests according to new admin cli implementation
  config-docs/pom.xml
  import-tool/src/docs/ops/import-tool.asciidoc
  import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java
Labels: 4.0

#365 updated to macOS
  import-tool/src/docs/ops/import-tool.asciidoc
Labels: 3.5

#366 Adapt doc tests
  kernel/src/test/java/examples/DeadlockDocTest.java
Labels: 4.0

#367 Added a section about the valid geographic coordinates
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
Labels: 4.0, cypher

#370 Update docs to use new transaction logs metrics.
  metrics-docs/pom.xml
Labels: 4.0

#377 Use proper test directory folder.
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/ExtensionTestingDocIT.java
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/JUnitDocIT.java
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/ExtensionTestingDocIT.java
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/JUnitDocIT.java
Labels: 4.0
