Repository neo4j/neo4j-documentation, pull requests merged in 2020-08, with the labels that each got.

#630 Bump jackson-databind from 2.9.10.1 to 2.9.10.5
  pom.xml
Labels: 4.2

#638 Add further information to admin/introduction section
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.1

#639 Add further information to admin/introduction section
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.2, cherry-picked

#640 Remove empty backup folder
  backup/pom.xml
Labels: 4.0, Dependencies w. other PR

#641 Remove empty backup folder
  backup/pom.xml
Labels: 4.1, cherry-picked

#642 Remove empty backup folder
  backup/pom.xml
Labels: 4.2, cherry-picked

#634 Add `OR REPLACE`, `IF NOT EXISTS` and `IF EXISTS` to create and drop commands for indexes and constraints
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: 4.2, cypher

#643 4.0 Mention indexes and constraints in naming rules.
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
Labels: 4.0, cypher

#644 4.1 Mention indexes and constraints in naming rules.
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
Labels: 4.1, cherry-picked, cypher

#645 4.2 Mention indexes and constraints in naming rules.
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
Labels: 4.2, cherry-picked, cypher

#646 Migrate File's to Path's
  cypher/cypher-docs/src/main/java/org/neo4j/cypher/example/JavaQuery.java
  doctools/src/main/java/org/neo4j/doc/GenerateConfigDocumentation.java
  embedded-examples/src/main/java/org/neo4j/examples/CalculateShortestPath.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jClusterUsingBuilder.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jClusterUsingNeo4jConf.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithBolt.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithCustomLogging.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithIndexing.java
  embedded-examples/src/main/java/org/neo4j/examples/NewMatrix.java
  embedded-examples/src/main/java/org/neo4j/examples/TerminateTransactions.java
  embedded-examples/src/main/java/org/neo4j/examples/TransactionEventListenerExample.java
  embedded-examples/src/main/java/org/neo4j/examples/TraversalExample.java
  embedded-examples/src/test/java/org/neo4j/examples/ReadOnlyDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/orderedpath/OrderedPathDocTest.java
  import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java
  metrics-docs/src/main/java/org/neo4j/metrics/docs/GenerateMetricsDocumentation.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 4.2
