Repository neo4j/neo4j-documentation, pull requests merged in 2020-03, with the labels that each got.

#518 Bump checkstyle from 8.18 to 8.29
  pom.xml
Labels: 4.0

#516 Added info about revoking compound privileges also revokes sub-privileges
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-create-drop-index-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/revoke-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.0, cypher

#477 Full-text analyzer stop words.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.0

#510 Including missing metrics in docs generation
  metrics-docs/pom.xml
Labels: 4.0, kernel

#513 Updated the docs for the compound privilege work
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/administration-security-administration-toc.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/AdministrationCommandTestBase.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabasePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/GraphPrivilegeTest.scala
Labels: 4.1, Dependencies w. other PR, cypher

#514 Updated the ref card to include DEFAULT DATABASE, TRANSACTION MANAGEMENT and USER MANAGEMENT
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabasePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementPrivilegeTest.scala
Labels: 4.1, cypher

#521 Added TRANSACTION MANAGEMENT where it was missed in the beginning of the database administration section
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
Labels: 4.1, cypher

#515 Added PUBLIC role to the cypher manual
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
Labels: 4.1, cypher

#522 Fix tests.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.1, cypher

#523 added a link from Reserved keywords page to the Naming rules
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
Labels: 3.5

#528 Add TransactionEventListener[] example tags
  embedded-examples/src/main/java/org/neo4j/examples/TransactionEventListenerExample.java
Labels: 4.0

#534 Remove errant comma in WHERE
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.0

#536 Edited the table descriptions
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/role-management-syntax.asciidoc
Labels: 4.1

#535 Changed "or" to "and"
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/admin-role-dbms.asciidoc
Labels: 4.1

#537 Edited the table descriptions in the user-management-privileges-command-syntax
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/user-management-syntax.asciidoc
Labels: 4.1

#524 Document new dbms privileges
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/admin-role-introduction.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/administration-security-administration-toc.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/admin-role-dbms.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/all-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/database-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/privilege-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabaseManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DbmsPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/PrivilegeManagementPrivilegeTest.scala
Labels: 4.1, cypher, enhancement

#538 Edited the table descriptions and the table columns
  cypher/cypher-docs/src/docs/dev/ql/administration/security/list-users-table-columns.asciidoc
Labels: 4.1

#525 Document `Anti` and `MultiNodeIndexSeek`
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.1, cypher

#540 edited the syntax descriptions
  FETCH_HEAD
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/constraint-management-syntax.asciidoc
Labels: 4.1

#539 Edited the command descriptions in the admin database syntax table.
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
Labels: 4.1

#541 Edited the table descriptions in the transaction management syntax page
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/transaction-management-syntax.asciidoc
Labels: 4.1

#542 Edited the index management syntax page
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/index-management-syntax.asciidoc
Labels: 4.1
