Repository neo4j/neo4j-documentation, pull requests merged in 2020-11, with the labels that each got.

#708 Update security and index deny example
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
Labels: 4.0, bug, cypher

#709 Update security and index deny example
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
Labels: 4.1, bug, cherry-picked, cypher

#710 Update security and index deny example
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
Labels: 4.2, bug, cherry-picked, cypher

#711 Update security and index deny example
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
Labels: 4.3, bug, cherry-picked, cypher

#701 SHOW INDEX and CONSTRAINT command and privilege
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/list-constraints-table-columns.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/list-indexes-table-columns.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/constraint-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/index-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabasePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: 4.2, cypher

#721 Switch the index and constraint descriptions
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
Labels: 4.1, cherry-picked

#712 fixed so that the default roles will be generated (#706)
  procedures/src/main/java/org/neo4j/doc/ProcedureReferenceGenerator.java
Labels: 4.1, cherry-picked

#713 fixed so that the default roles will be generated (#706)
  procedures/src/main/java/org/neo4j/doc/ProcedureReferenceGenerator.java
Labels: 4.2, cherry-picked

#724 SHOW INDEX and CONSTRAINT command and privilege
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/list-constraints-table-columns.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/list-indexes-table-columns.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/constraint-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/index-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabasePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: 4.3, cherry-picked, cypher

#733 fixed broken link
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.2, cherry-pick-this-to-4.3

#736 fixed broken link to neo4j-procedures
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.1

#737 fixed broken link for neo4j-procedures
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.3

#735 fixed broken link to neo4j-procedures
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.0

#730 Fix missing EXECUTE in EXECUTE ADMIN PROCEDURES
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/execute-syntax.asciidoc
Labels: 4.2, cypher

#731 Fix missing EXECUTE in EXECUTE ADMIN PROCEDURES
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/execute-syntax.asciidoc
Labels: 4.3, cherry-picked, cypher

#722 Switch the index and constraint descriptions
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
Labels: 4.2, cherry-picked

#723 Switch the index and constraint descriptions
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
Labels: 4.3, cherry-picked

#726 update syntax for existence constraints
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/JUnitDocIT.java
Labels: 4.3, cypher

#740 updated poms that I had missed
  config-docs/pom.xml
  cypher/pom.xml
  doctools/pom.xml
  embedded-examples/pom.xml
  graphviz/pom.xml
  import-tool/pom.xml
  jmx/pom.xml
  kernel/pom.xml
  metrics-docs/pom.xml
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-test/pom.xml
  procedures/pom.xml
  server-docs/pom.xml
  server-examples/pom.xml
  server-test-utils/pom.xml
  test-framework/pom.xml
Labels: 4.0, THIS VERSION ONLY

#738 Update Cypher versions for 4.3.
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: 4.3, Dependencies w. other PR, cypher

#718 Document ShortestPath operator.
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.3, cypher

#761 Resolve the part-bold line in settings tables
  config-docs/src/main/java/org/neo4j/doc/ConfigDocsGenerator.java
  doctools/src/main/java/org/neo4j/doc/SettingsDocumenter.java
  doctools/src/test/java/org/neo4j/doc/SettingsDocumenterTest.java
Labels: 4.3, cherry-picked

#720 split content across multiple files
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-db-hits.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans.asciidoc
Labels: 4.1, cherry-pick-this-forward

#734 Additional SHOW INDEXES/CONSTRAINTS documentation
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/list-constraints-table-columns.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/list-indexes-table-columns.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
Labels: 4.2, cherry-pick-this-forward, cypher

#746 The label/type list of entity is not optional and other small syntax updates
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/revoke-syntax.asciidoc
Labels: 4.0, THIS VERSION ONLY, cypher

#751 Don't use old create index syntax
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShortestPathPlanningTest.scala
Labels: 4.0, cherry-pick-this-forward, cypher

#739 Update glossary and prettifier parser after OPTIONS
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
Labels: 4.2, cherry-pick-this-forward, cypher

#759 Resolve the part-bold line in settings tables
  config-docs/src/main/java/org/neo4j/doc/ConfigDocsGenerator.java
  doctools/src/main/java/org/neo4j/doc/SettingsDocumenter.java
  doctools/src/test/java/org/neo4j/doc/SettingsDocumenterTest.java
Labels: 4.1, cherry-picked

#760 Resolve the part-bold line in settings tables
  config-docs/src/main/java/org/neo4j/doc/ConfigDocsGenerator.java
  doctools/src/main/java/org/neo4j/doc/SettingsDocumenter.java
  doctools/src/test/java/org/neo4j/doc/SettingsDocumenterTest.java
Labels: 4.2, cherry-picked

#769 Don't use old create index syntax
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShortestPathPlanningTest.scala
Labels: 4.1, cherry-picked

#772 Escape the asterisks so they avoid the bold block (in the MATCH privilege section)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.0, bug, cherry-pick-this-forward

#773 Escape the asterisks so they avoid the bold block (in the name-globbing section)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.2, bug, cherry-pick-this-forward

#714 fixed so that the default roles will be generated (#706)
  procedures/src/main/java/org/neo4j/doc/ProcedureReferenceGenerator.java
Labels: 4.3, cherry-picked

#770 Don't use old create index syntax
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShortestPathPlanningTest.scala
Labels: 4.2, cherry-picked

#774 Escape the asterisks so they avoid the bold block
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
Labels: 4.1, cherry-picked

#775 Escape the asterisks so they avoid the bold block
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
Labels: 4.2, cherry-picked

#776 Escape the asterisks so they avoid the bold block
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
Labels: 4.3, cherry-picked

#777 Escape the asterisks so they avoid the bold block (in the name-globbing section)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.3, cherry-picked

#753 Add some structure to the list privilege section
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-privileges-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.2, cherry-pick-this-forward, cypher

#752 Add some structure to the list privilege section
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-privileges-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.1, THIS VERSION ONLY, cypher

#778 Add some structure to the list privilege section
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-privileges-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.3, cherry-picked, cypher

#765 split content across multiple files (#720)
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-db-hits.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans.asciidoc
Labels: 4.2, cherry-picked

#748 Add back `REVOKE ROLE role FROM user` in syntax table and other syntax updates
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/all-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/transaction-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/revoke-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/BuiltInRolesAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.2, cherry-pick-this-forward, cypher

#785 Add back `REVOKE ROLE role FROM user` in syntax table and other syntax updates
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/all-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/transaction-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/revoke-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/BuiltInRolesAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.3, cherry-picked, cypher

#771 Don't use old create index syntax
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShortestPathPlanningTest.scala
Labels: 4.3, cherry-picked

#743 removed typo
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
Labels: 4.0, cherry-pick-this-forward

#762 Update to `[, ...]` instead of plural name to indicate comma separated list
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-write-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-write-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/revoke-syntax.asciidoc
Labels: 4.0, THIS VERSION ONLY, cypher

#787 removed typo (#743)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
Labels: 4.1, cherry-picked

#788 removed typo (#743)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
Labels: 4.2, cherry-picked

#789 removed typo (#743)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
Labels: 4.3, cherry-picked

#744 all relationships have a direction
  cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc
Labels: 4.0, cherry-pick-this-forward

#742 reworked the path uniqueness page
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.0, cherry-pick-this-forward, cypher

#790 all relationships have a direction (#744)
  cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc
Labels: 4.1, cherry-picked

#792 all relationships have a direction (#744)
  cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc
Labels: 4.3, cherry-picked

#763 Updates around comma separated lists
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/all-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/constraint-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/index-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/name-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/transaction-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-all-graph-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-remove-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-write-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-all-graph-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-merge-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-remove-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-write-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/revoke-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-all-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/show-databases-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityWritePrivilegesTest.scala
Labels: 4.1, THIS VERSION ONLY, cypher

#764 Updates around comma separated lists
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/databases-command-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/all-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/constraint-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/index-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/name-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/transaction-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/execute-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-all-graph-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-remove-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-write-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-all-graph-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-merge-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-remove-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-write-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/revoke-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-all-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityWritePrivilegesTest.scala
Labels: 4.2, cherry-pick-this-forward, cypher

#798 4.2.2-SNAPSHOT
  server-test-utils/pom.xml
Labels: 4.2, THIS VERSION ONLY

#796 Updates around comma separated lists
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/databases-command-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/all-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/constraint-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/deny-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-access-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-start-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/grant-database-stop-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/index-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/name-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/transaction-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/execute-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-all-graph-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-remove-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-write-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-all-graph-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-merge-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-remove-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-label-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-write-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/revoke-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-all-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityWritePrivilegesTest.scala
Labels: 4.3, cherry-picked, cypher

#791 all relationships have a direction (#744)
  cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc
Labels: 4.2, cherry-picked

#797 Fixed a typo and toc for introduction
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.0, cherry-pick-this-forward

#793 reworked the path uniqueness page (#742)
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.1, cherry-picked

#794 reworked the path uniqueness page (#742)
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.2, cherry-picked

#799 Fixed a typo and toc for introduction (#797)
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.1, cherry-picked
