Repository neo4j/neo4j-documentation, pull requests merged in 2020-06, with the labels that each got.

#586 Improved the ACCESS privilege definition
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.0

#600 Fixed docs compilation after recent 4.1 refactoring
  metrics-docs/pom.xml
Labels: 4.1, bug

#601 Add link to privileges required for commands
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
Labels: 4.1, cypher, enhancement

#588 Wrap the added information to Advanced query tuning example in an admonition
  cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
Labels: 4.1

#591 SHOW USER PRIVILEGES and non-native auth providers
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.1, cypher

#593 SHOW USER PRIVILEGES and non-native auth providers
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.0, cypher

#602 Document discovery metrics in separate class
  metrics-docs/pom.xml
Labels: 4.1

#596 Add link how to restore admin
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.0, cypher, enhancement

#598 Document options for DROP DATABASE
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.1, causal clustering, cypher

#603 Privileges of built-in roles and how to recreate them
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/BuiltInRolesAdministrationTest.scala
Labels: 4.1, Dependencies w. other PR, cypher

#592 Embedded examples for clustering
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jClusterUsingBuilder.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jClusterUsingNeo4jConf.java
Labels: 4.1, causal clustering

#599 4.1 show where yield
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-all-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/show-databases-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
Labels: 4.1, cypher

#604 Add new section to Introduction/Transactions
  cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
Labels: 4.1

#605 Update definitions on the Introduction/Databases page
  cypher/cypher-docs/src/docs/dev/general/databases-and-graphs.asciidoc
Labels: 4.1

#606 Update the USE clause for 4.1 Fabric details
  cypher/cypher-docs/src/docs/dev/query-use.adoc
Labels: 4.1

#609 3.5.20-SNAPSHOT pom changes
  backup/pom.xml
  config-docs/pom.xml
  contents/pom.xml
  cypher/cypher-docs/pom.xml
  cypher/cypher-prettifier/pom.xml
  cypher/graphgist/pom.xml
  cypher/pom.xml
  cypher/refcard-tests/pom.xml
  doctools/pom.xml
  embedded-examples/pom.xml
  graphviz/pom.xml
  ha-docs/pom.xml
  import-tool/pom.xml
  jmx/pom.xml
  kernel/pom.xml
  lucene/pom.xml
  metrics-docs/pom.xml
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-test/pom.xml
  pom.xml
  procedures/pom.xml
  server-docs/pom.xml
  server-examples/pom.xml
  server-test-utils/pom.xml
  test-framework-enterprise/pom.xml
  test-framework/pom.xml
Labels: 3.5

#608 Add queryId format change to Cypher Manual
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.1

#611 Bump version to 4.0.7-SNAPSHOT
  config-docs/pom.xml
  cypher/cypher-docs/pom.xml
  cypher/cypher-prettifier/pom.xml
  cypher/graphgist/pom.xml
  cypher/pom.xml
  cypher/refcard-tests/pom.xml
  doctools/pom.xml
  embedded-examples/pom.xml
  graphviz/pom.xml
  import-tool/pom.xml
  jmx/pom.xml
  kernel/pom.xml
  metrics-docs/pom.xml
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-test/pom.xml
  pom.xml
  procedures/pom.xml
  server-docs/pom.xml
  server-examples/pom.xml
  server-test-utils/pom.xml
  test-framework/pom.xml
Labels: 4.0

#610 Fix failing test
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.2

#607 4.1 fabric administration updates
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
Labels: 4.1

#613 Use Slotted runtime for LetSelectOr(Anti)SemiApply
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.2, cypher

#616 Migrate File's to Path's where they are deprecated
  cypher/cypher-docs/src/main/java/org/neo4j/cypher/example/JavaQuery.java
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/IntroDocTest.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/CypherDoc.java
  cypher/graphgist/src/test/java/org/neo4j/doc/cypherdoc/BlockTypeTest.java
  embedded-examples/src/main/java/org/neo4j/examples/CalculateShortestPath.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jClusterUsingBuilder.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jClusterUsingNeo4jConf.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithBolt.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithCustomLogging.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithIndexing.java
  embedded-examples/src/main/java/org/neo4j/examples/NewMatrix.java
  embedded-examples/src/main/java/org/neo4j/examples/TerminateTransactions.java
  embedded-examples/src/main/java/org/neo4j/examples/TransactionEventListenerExample.java
  embedded-examples/src/main/java/org/neo4j/examples/TraversalExample.java
  embedded-examples/src/main/java/org/neo4j/examples/orderedpath/OrderedPath.java
  embedded-examples/src/test/java/org/neo4j/doc/metatest/TestJavaTestDocsGenerator.java
  embedded-examples/src/test/java/org/neo4j/examples/CalculateShortestPathTest.java
  embedded-examples/src/test/java/org/neo4j/examples/Neo4jBasicDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/ProcedureExampleDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/ReadOnlyDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/StartWithConfigurationDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/backup/TestBackup.java
  embedded-examples/src/test/java/org/neo4j/examples/orderedpath/OrderedPathDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/socnet/SocnetTest.java
  graphviz/src/main/java/org/neo4j/visualization/graphviz/Script.java
  graphviz/src/test/java/org/neo4j/visualization/graphviz/TestGraphvizSubgraphOutput.java
  graphviz/src/test/java/org/neo4j/visualization/graphviz/TestNewGraphvizWriter.java
  import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java
  procedures/src/main/java/org/neo4j/doc/Neo4jInstance.java
  procedures/src/main/java/org/neo4j/doc/ProcedureReferenceGenerator.java
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerTestUtils.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 4.2

#617 Add missing cacheFactory to ExecutionEngineFactory
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ExecutionEngineFactory.scala
Labels: 4.2, cypher
