Repository neo4j/neo4j-documentation, pull requests merged in 2020-09, with the labels that each got.

#647 Replace usage of sub-graph with path
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MatchTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 3.5

#652 Replace usage of sub-graph with path
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MatchTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.2, cherry-picked

#651 Replace usage of sub-graph with path
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MatchTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.1, cherry-picked

#650 Replace usage of sub-graph with path
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MatchTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.0, cherry-picked

#649 And RETURN examples to SHOW USERS/PRIVILEGES/DATABASES
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-all-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/show-databases-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
Labels: 4.2, cypher

#637 4.0 Limitations of security
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-db-operations.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-labels.asciidoc
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityKnownLimitationsTest.scala
Labels: 4.0, cypher

#648 Document discovery metrics in separate class
  metrics-docs/pom.xml
Labels: 4.0, THIS VERSION ONLY

#659 Fix broken links
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/Document.scala
Labels: 4.2, bug

#661 Make sure nodes are connected to the tx in which they are used.
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
Labels: 4.1

#665 Make sure nodes are connected to the tx in which they are used.
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
Labels: 4.0, cherry-picked

#666 Make sure nodes are connected to the tx in which they are used.
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
Labels: 4.2, cherry-picked

#658 moved security introduction
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.0

#657 Add a parameter whether the container should start on random ports.
  server-docs/src/test/java/org/neo4j/doc/server/NeoServerJAXRSDocIT.java
  server-test-utils/src/main/java/org/neo4j/doc/server/SharedWebContainerTestBase.java
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/WebContainerHelper.java
Labels: 4.1

#670 Add a parameter whether the container should start on random ports or…
  server-docs/src/test/java/org/neo4j/doc/server/NeoServerJAXRSDocIT.java
  server-test-utils/src/main/java/org/neo4j/doc/server/SharedWebContainerTestBase.java
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/WebContainerHelper.java
Labels: 4.2

#656 Document encrypted password command
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-alter-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-create-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
Labels: 4.2, Dependencies w. other PR, cypher

#663 Fix broken links
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.1, bug, cherry-picked

#673 Bump ant version
  config-docs/pom.xml
  metrics-docs/pom.xml
  server-docs/pom.xml
Labels: 4.2, cherry-picked

#671 Remove OR REPLACE for indexes and constraints.
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: 4.2, Dependencies w. other PR, cypher

#662 Fix broken link
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.0, bug, cherry-picked

#654 Add notices for `USE` and `PERIODIC COMMIT` not working together
  cypher/cypher-docs/src/docs/dev/query-use.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.1, cypher

#653 Add notices for `USE` and `PERIODIC COMMIT` not working together
  cypher/cypher-docs/src/docs/dev/query-use.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.2, cherry-picked, cypher
