Repository neo4j/neo4j-documentation, pull requests merged in 2020-12, with the labels that each got.

#801 Set version to 4.1.6-SNAPSHOT
  config-docs/pom.xml
  cypher/cypher-docs/pom.xml
  cypher/cypher-prettifier/pom.xml
  cypher/graphgist/pom.xml
  cypher/pom.xml
  cypher/refcard-tests/pom.xml
  doctools/pom.xml
  embedded-examples/pom.xml
  graphviz/pom.xml
  import-tool/pom.xml
  jmx/pom.xml
  kernel/pom.xml
  metrics-docs/pom.xml
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-test/pom.xml
  pom.xml
  procedures/pom.xml
  server-docs/pom.xml
  server-examples/pom.xml
  server-test-utils/pom.xml
  test-framework/pom.xml
Labels: 4.1

#800 Fixed a typo and toc for introduction (#797)
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.2, cherry-picked

#795 reworked the path uniqueness page (#742)
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.3, cherry-picked

#802 Fixed a typo and toc for introduction (#797)
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.3, cherry-picked

#803 Add direct dependency on neo4j-kernel.
  cypher/cypher-prettifier/pom.xml
Labels: 4.3, cypher

#804 Add escape chars to work with pdf and html
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.2

#786 restore includes and update how toc is hidden
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans.asciidoc
Labels: 4.2, cherry-pick-this-to-4.1, cherry-pick-this-to-4.3

#808 restore includes and update how toc is hidden (#786)
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans.asciidoc
Labels: 4.1, cherry-picked

#807 restore includes and update how toc is hidden (#786)
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans.asciidoc
Labels: 4.3, cherry-picked

#806 Add escape chars to work with pdf and html (#804)
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
Labels: 4.3, cherry-picked

#812 add USE test
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UseTest.scala
Labels: 4.1, Dependencies w. other PR, cherry-pick-this-to-4.2, cherry-pick-this-to-4.3

#749 Deprecation of exists() for property checks
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/query-tuning-indexes.adoc
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShortestPathPlanningTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ListPredicatesTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/PredicatesTest.scala
Labels: 4.3, Dependencies w. other PR, cypher

#815 4.3 cherry pick 812
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UseTest.scala
Labels: 4.3, cherry-picked

#814 4.2-cherry-pick-812 (#812)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UseTest.scala
Labels: 4.2, cherry-picked

#781 Add privilege hierarchy images
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.0, Dependencies w. other PR, THIS VERSION ONLY, cypher

#813 Update heading level
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
Labels: 4.2, cherry-pick-this-to-4.3

#782 Add privilege hierarchy images
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.1, Dependencies w. other PR, THIS VERSION ONLY, cypher

#783 Add privilege hierarchy images
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.2, Dependencies w. other PR, THIS VERSION ONLY, cypher

#818 Fix failing build caused by assuming implementation of QueryStatistics
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/DocsExecutionResult.scala
Labels: 4.3, bug

#784 Add privilege hierarchy images
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.3, Dependencies w. other PR, cypher

#819 Fix port clashes on online backup and rest server to allow tests to run alongside a neo4j server
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/pom.xml
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  embedded-examples/src/test/java/org/neo4j/examples/backup/TestBackup.java
  procedures/src/main/java/org/neo4j/doc/Neo4jInstance.java
  server-docs/src/test/java/org/neo4j/doc/server/NeoServerJAXRSDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/TransactionTimeoutDocIT.java
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/CommunityServerTestBase.java
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 4.1, THIS VERSION ONLY, cherry-picked, cypher, tooling

#821 Update heading level (#813)
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
Labels: 4.0, cherry-picked

#816 Update heading level (#813)
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
Labels: 4.3, cherry-picked

#817 Improve default database per user docs
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-alter-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-create-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
Labels: 4.3, cypher

#823 Update default for connectComponentsPlanner
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: 4.3, cypher

#824 More name clean-up
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
Labels: 4.0, THIS VERSION ONLY, cypher

#828 DropResult has been removed from the product
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.3, bug, cypher

#825 More name clean-up
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-merge-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
Labels: 4.1, cherry-pick-this-forward, cypher

#829 More name clean-up
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-merge-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
Labels: 4.2, cherry-picked, cypher

#830 More name clean-up
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/deny-traverse-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-create-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-delete-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-match-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-merge-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-read-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-set-property-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-traverse-syntax.asciidoc
Labels: 4.3, cherry-picked, cypher

#822 Update heading level (#813)
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
Labels: 4.1, cherry-picked

#832 cherry-picked (#720)
  cypher/cypher-docs/src/docs/dev/execution-plans-db-hits.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans.asciidoc
Labels: 4.3, cherry-picked

#834 update driver manual links to docs page
  cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
Labels: 4.2, cherry-pick-this-forward

#835 update driver manual links to docs page (#834)
  cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
Labels: 4.3, cherry-picked

#827 Update to not use `all of the above` since that can be confusing
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/database-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.1, cherry-pick-this-forward, cypher

#836 Update to not use `all of the above` since that can be confusing
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/database-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.2, cherry-picked, cypher

#837 Update to not use `all of the above` since that can be confusing
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/database-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: 4.3, cherry-picked, cypher
