Repository neo4j/neo4j-documentation, pull requests merged in 2021-12, with the labels that each got.

#1331 Adapt tests to api cleanup
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jClusterUsingNeo4jConf.java
  embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithCustomLogging.java
  embedded-examples/src/test/java/org/neo4j/examples/StartWithConfigurationDocTest.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/WebContainerHelper.java
Labels: 5.0

#1332 fix link to user-defined procedures
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.0, cherry-pick-this-forward

#1330 fix rendering issue in deprecations table
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.4, cherry-pick-this-to-5.0

#1333 fix rendering issue in table by removing indent (#1330)
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cherry-picked, 5.0

#1334 fix link to user-defined procedures (#1332)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.1, cherry-picked

#1335 fix link to user-defined procedures (#1332)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.2, cherry-picked

#1336 fix link to user-defined procedures (#1332)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: cherry-picked, 4.3

#1337 fix link to user-defined procedures (#1332)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: cherry-picked, 4.4

#1325 Fix broken refcard test by loosing up the assertion
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ShowProcFuncTest.scala
Labels: cypher, 5.0

#1327 Remove use of DROP INDEX/CONSTRAINT by schema
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/examples.adoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/syntax.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
Labels: cypher, 5.0
