Repository neo4j/neo4j-documentation, pull requests merged in 2021-02, with the labels that each got.

#897 licence update
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/BuiltInRolesAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityWritePrivilegesTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabaseManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DbmsPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/GraphWritePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/PrivilegeManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UseTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementPrivilegeTest.scala
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/TestWebContainer.java
Labels: 4.1, cherry-pick-this-forward

#898 licence update (#897)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/BuiltInRolesAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityWritePrivilegesTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabaseManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DbmsPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/GraphWritePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/PrivilegeManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UseTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementPrivilegeTest.scala
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/TestWebContainer.java
Labels: 4.2, cherry-picked

#899 licence update (#897)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/BuiltInRolesAdministrationTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityReadPrivilegesTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityWritePrivilegesTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabaseManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DbmsPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/GraphWritePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/PrivilegeManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UseTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementPrivilegeTest.scala
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/TestWebContainer.java
Labels: 4.3, cherry-picked

#900 added licence text
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PrivilegesTestBase.scala
Labels: 4.2, cherry-pick-this-forward

#901 added licence text (#900)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PrivilegesTestBase.scala
Labels: 4.3, cherry-picked

#896 properly excaped Cypher query
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.0, bug, cherry-pick-this-forward

#902 properly excaped Cypher query (#896)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.1, cherry-picked

#903 properly excaped Cypher query (#896)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.2, cherry-picked

#904 properly excaped Cypher query (#896)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.3, cherry-picked

#892 Indexes are case sensitive
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: 4.0, cherry-pick-this-forward, cypher

#906 Revert "Documentation for CREATE / ALTER USER SET DEFAULT DATABASE ..."
  cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-role-database.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/dbms/user-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/list-users-table-columns.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-alter-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-create-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
Labels: 4.3, cypher

#907 Indexes are case sensitive
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: 4.1, cherry-picked

#908 Indexes are case sensitive
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: 4.2, cherry-picked

#909 Indexes are case sensitive
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: 4.3, cherry-picked

#889 prettifier disabled
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/StringFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/Document.scala
Labels: 4.0, cherry-pick-this-forward

#911 prettifier disabled (#889)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/StringFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/Document.scala
Labels: 4.1, cherry-picked

#910 4.0 procedure call implicit explicit
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.0, cherry-pick-this-forward

#912 prettifier disabled (#889)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/StringFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/Document.scala
Labels: 4.2, cherry-picked

#913 prettifier disabled (#889)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/StringFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/Document.scala
Labels: 4.3, cherry-picked

#914 4.0 procedure call implicit explicit (#910)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.1, cherry-picked

#915 4.0 procedure call implicit explicit (#910)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.2, cherry-picked

#916 4.0 procedure call implicit explicit (#910)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: 4.3, cherry-picked

#917 removed bullet points and fixed a bug
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
Labels: 4.0, cherry-pick-this-forward

#919 removed bullet points and fixed a bug (#917)
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
Labels: 4.1, cherry-picked

#920 removed bullet points and fixed a bug (#917)
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
Labels: 4.2, cherry-picked

#921 removed bullet points and fixed a bug (#917)
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
Labels: 4.3, cherry-picked

#923 Update plan descriptions after recent refactoring.
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.3, cypher

#918 fixed some asciidoc syntax
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.0, cherry-pick-this-forward

#926 fixed some asciidoc syntax (#918)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.3, cherry-picked

#882 Autogenerate function descriptions
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MathematicalLogarithmicFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MathematicalNumericFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MathematicalTrigonometricFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/StringFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalDurationFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
  functions/pom.xml
  functions/src/main/java/org/neo4j/doc/FunctionDescriptionsGenerator.java
  functions/src/main/java/org/neo4j/doc/GenerateFunctionDescriptions.java
  functions/src/main/java/org/neo4j/doc/Neo4jInstance.java
  pom.xml
Labels: 4.3, cypher

#924 4.1 cherry pick 918
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.1, cherry-picked

#925 fixed some asciidoc syntax (#918)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.2, cherry-picked

#861 Overhaul the Cypher hint section.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.3, cypher

#928 4.0 cypher query fix
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
Labels: 4.0, cherry-pick-this-forward

#930 4.0 cypher query fix (#928)
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
Labels: 4.1, cherry-picked

#932 4.0 cypher query fix (#928)
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
Labels: 4.3, cherry-picked

#931 4.0 cypher query fix (#928)
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
  cypher/cypher-docs/src/docs/graphgists/uniqueness/uniqueness.asciidoc
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
Labels: 4.2, cherry-picked

#933 4.0 cypher query syntax fix part 2
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.0, cherry-pick-this-forward

#884 Add `CALL ... YIELD *` to procedure docs
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/CallTest.scala
Labels: 4.3, cypher

#936 4.0 cypher query syntax fix part 2 (#933)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.2, cherry-picked

#929 Add `IF EXISTS` to `ALTER USER`
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-alter-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementTest.scala
Labels: 4.3, cypher

#935 4.0 cypher query syntax fix part 2 (#933)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.1, cherry-picked

#937 4.0 cypher query syntax fix part 2 (#933)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.3, cherry-picked

#938 fixed Cypher query syntax for Spatial
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
Labels: 4.0, cherry-pick-this-forward

#940 fixed Cypher query syntax for Spatial (#938)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
Labels: 4.2, cherry-picked

#941 fixed Cypher query syntax for Spatial (#938)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
Labels: 4.3, cherry-picked

#939 fixed Cypher query syntax for Spatial (#938)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
Labels: 4.1, cherry-picked

#934 fixed Cypher style for Temporal values
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.0, cherry-pick-this-forward

#942 fixed Cypher style for Temporal values (#934)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.1, cherry-picked

#943 fixed Cypher style for Temporal values (#934)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.2, cherry-picked

#945 fixed Cypher syntax for Maps
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MapsTest.scala
Labels: 4.0, cherry-pick-this-forward

#944 fixed Cypher style for Temporal values (#934)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.3, cherry-picked

#946 fixed Cypher syntax for Maps (#945)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MapsTest.scala
Labels: 4.1, cherry-picked

#948 fixed Cypher syntax for Maps (#945)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MapsTest.scala
Labels: 4.3, cherry-picked

#947 fixed Cypher syntax for Maps (#945)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MapsTest.scala
Labels: 4.2, cherry-picked

#950 revert changes to lower case
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
Labels: 4.0, cherry-pick-this-forward

#949 fixed style and rendering bugs
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
Labels: 4.0, cherry-pick-this-forward

#952 revert changes to lower case (#950)
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
Labels: 4.2, cherry-picked

#954 fixed style and rendering bugs (#949)
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
Labels: 4.1, cherry-picked

#956 fixed style and rendering bugs (#949)
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
Labels: 4.3, cherry-picked

#951 revert changes to lower case (#950)
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
Labels: 4.1, cherry-picked

#953 revert changes to lower case (#950)
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
Labels: 4.3, cherry-picked

#955 fixed style and rendering bugs (#949)
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
Labels: 4.2, cherry-picked

#957 4.0 cypher query syntax fix part 7
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MatchTest.scala
Labels: 4.0, cherry-pick-this-forward

#958 4.0 cypher query syntax fix part 7 (#957)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MatchTest.scala
Labels: 4.1, cherry-picked

#959 4.0 cypher query syntax fix part 7 (#957)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MatchTest.scala
Labels: 4.2, cherry-picked

#960 4.0 cypher query syntax fix part 7 (#957)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MatchTest.scala
Labels: 4.3, cherry-picked

#961 4.0 cypher query syntax fix part 8
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OptionalMatchTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ReturnTest.scala
Labels: 4.0, cherry-pick-this-forward

#966 4.0 cypher query syntax fix part 8 (#961)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OptionalMatchTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ReturnTest.scala
Labels: 4.1, cherry-picked

#967 4.0 cypher query syntax fix part 8 (#961)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OptionalMatchTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ReturnTest.scala
Labels: 4.2, cherry-picked

#968 4.0 cypher query syntax fix part 8 (#961)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OptionalMatchTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ReturnTest.scala
Labels: 4.3, cherry-picked
