Repository neo4j/neo4j-documentation, pull requests merged in 2021-04, with the labels that each got.

#1056 improved content with abstract
  cypher/cypher-docs/src/docs/dev/syntax/comments.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/variables.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/working-with-null.asciidoc
Labels: 4.0, cherry-pick-this-forward

#1072 improved content with abstract (#1056)
  cypher/cypher-docs/src/docs/dev/syntax/comments.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/variables.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/working-with-null.asciidoc
Labels: 4.1, cherry-picked

#1073 improved content with abstract (#1056)
  cypher/cypher-docs/src/docs/dev/syntax/comments.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/variables.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/working-with-null.asciidoc
Labels: 4.2, cherry-picked

#1069 Enable relationship property indexes feature flag for docs
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: 4.3

#1077 Adapt ReadOnlyDocTest
  embedded-examples/src/test/java/org/neo4j/examples/ReadOnlyDocTest.java
Labels: 4.3

#1076 Documenting the new conversion functions
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/StringFunctionsTest.scala
Labels: 4.3, cypher

#1074 improved content with abstract (#1056)
  cypher/cypher-docs/src/docs/dev/syntax/comments.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/naming.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/reserved.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/variables.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/working-with-null.asciidoc
Labels: 4.3, cherry-picked

#1080 Update plan descriptions after recent refactoring.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.3, cypher

#1078 Bump guava from 27.1-jre to 29.0-jre
  pom.xml
Labels: 4.3

#1085 Update plan descriptions after recent refactoring.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.3, cypher

#1086 Change artefacts version to 3.5.29
  backup/pom.xml
  config-docs/pom.xml
  contents/pom.xml
  cypher/cypher-docs/pom.xml
  cypher/cypher-prettifier/pom.xml
  cypher/graphgist/pom.xml
  cypher/pom.xml
  cypher/refcard-tests/pom.xml
  doctools/pom.xml
  embedded-examples/pom.xml
  graphviz/pom.xml
  ha-docs/pom.xml
  import-tool/pom.xml
  jmx/pom.xml
  kernel/pom.xml
  lucene/pom.xml
  metrics-docs/pom.xml
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-test/pom.xml
  pom.xml
  procedures/pom.xml
  server-docs/pom.xml
  server-examples/pom.xml
  server-test-utils/pom.xml
  test-framework-enterprise/pom.xml
  test-framework/pom.xml
Labels: 3.5

#1075 Document creating, dropping and listing lookup indexes
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/export/SubGraphExporter.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LookupIndexTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: 4.3, cypher

#1079 documenting create database options
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/databases-command-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/Main.java
Labels: 4.3, cypher
