Repository neo4j/neo4j-documentation, pull requests merged in 2021-01, with the labels that each got.

#838 Improvements to syntax summaries section
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
Labels: 4.0, cherry-pick-this-forward, cypher

#842 Improvements to syntax summaries section
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
Labels: 4.2, cherry-picked, cypher

#843 Improvements to syntax summaries section
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
Labels: 4.3, cherry-picked, cypher

#841 Improvements to syntax summaries section
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
Labels: 4.1, cherry-picked, cypher

#844 fixed bug
  cypher/cypher-docs/src/docs/dev/ql/administration/databases-command-syntax.asciidoc
Labels: 4.2, cherry-pick-this-to-4.3

#846 Fix build failure
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.3, bug, cypher

#845 fixed bug (#844)
  cypher/cypher-docs/src/docs/dev/ql/administration/databases-command-syntax.asciidoc
Labels: 4.3, cherry-picked

#840 Fix operators comparison docs
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 3.5, cherry-pick-this-forward

#850 Fix operators comparison docs (#840)
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.0, cherry-picked

#852 Fix operators comparison docs (#840)
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.2, cherry-picked

#853 Fix operators comparison docs (#840)
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.3, cherry-picked

#854 added filtering info to various refcards (#847)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabaseManagementTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ListPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/RoleManagementTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementTest.scala
Labels: 4.2, cherry-picked

#855 added filtering info to various refcards (#847)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabaseManagementTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ListPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/RoleManagementTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementTest.scala
Labels: 4.3, cherry-picked

#831 Add missing section to administration toc
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.1, cherry-pick-this-forward, cypher

#849 Add missing section to administration toc
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.0, THIS VERSION ONLY, cypher

#860 Move sentence to the right paragraph
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
Labels: 4.3

#856 Update CREATE and ALTER USER to not have required order of SET clauses
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-alter-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
Labels: 4.3, cypher

#858 Add missing section to administration toc
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.2, cherry-picked

#859 Add missing section to administration toc
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.3, cherry-picked

#857 Document Auto-Parameterization.
  cypher/cypher-docs/src/docs/dev/syntax/parameters.asciidoc
Labels: 4.3, cypher

#848 Document behavior of LIMIT on side effects
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LimitTest.scala
Labels: 4.3

#865 removed bullet points
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.0, cherry-pick-this-forward

#866 removed bullet points (#865)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.1, cherry-picked

#867 removed bullet points (#865)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.2, cherry-picked

#868 removed bullet points (#865)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.3, cherry-picked

#864 Bump jackson-databind from 2.9.10.5 to 2.9.10.7
  pom.xml
Labels: 4.3

#839 Add missing temporal accessors
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 3.5, cherry-pick-this-forward, cypher, enhancement

#870 Add missing temporal accessors
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.0, cherry-picked

#871 Add missing temporal accessors
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.1, cherry-picked

#872 Add missing temporal accessors
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.2, cherry-picked

#873 Add missing temporal accessors
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.3, cherry-picked

#878 Added link to procedures
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.0, cherry-pick-this-forward

#869 Generate metrics by service loading instead of hardcoded list
  metrics-docs/pom.xml
  metrics-docs/src/main/java/org/neo4j/metrics/docs/GenerateMetricsDocumentation.java
  metrics-docs/src/main/java/org/neo4j/metrics/docs/MetricsAsciiDocGenerator.java
Labels: 4.3, Dependencies w. other PR

#883 4.0 clause foreach improvement
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ForeachTest.scala
Labels: 4.0, cherry-pick-this-forward

#879 Added link to procedures (#878)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.1, cherry-picked

#880 Added link to procedures (#878)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.2, cherry-picked

#881 Added link to procedures (#878)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 4.3, cherry-picked

#886 4.0 clause foreach improvement (#883)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ForeachTest.scala
Labels: 4.2, cherry-picked

#885 4.0 clause foreach improvement (#883)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ForeachTest.scala
Labels: 4.1, cherry-picked

#887 4.0 clause foreach improvement (#883)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ForeachTest.scala
Labels: 4.3, cherry-picked
