Repository neo4j/neo4j-documentation, pull requests merged in 2021-07, with the labels that each got.

#1154 Adapt build to product changes
  cypher/cypher-docs/pom.xml
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/ExtensionTestingDocIT.java
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/JUnitDocIT.java
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/ExtensionTestingDocIT.java
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/JUnitDocIT.java
  server-test-utils/src/main/java/org/neo4j/doc/server/SharedWebContainerTestBase.java
Labels: 4.4, bug, enhancement

#1147 Document multiple hints to solve a disjunction
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.4, cypher, team-planner

#1149 Cleanup after Prettifier was ditched.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalDurationFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/DocBuilder.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/Document.scala
Labels: 4.4, cypher

#1153 Improved messaging around duration components
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.3, cherry-pick-this-forward, cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cypher

#1160 Improved messaging around duration components
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.4, cherry-picked

#1161 Improved messaging around duration components
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.2, cherry-picked

#1162 Improved messaging around duration components
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.1, cherry-picked

#1163 Improved messaging around duration components
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.0, cherry-picked

#1164 Improved messaging around duration components
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 3.5, cherry-picked

#1165 Add test for LOAD CSV from remote file
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 3.5, cherry-pick-this-forward

#1155 Add paragraph about needing privileges to create and drop indexes and constraints
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.0, THIS VERSION ONLY, cypher

#1167 cherry-picked from 3.5
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.1, cherry-picked

#1168 cherry-picked from 3.5
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.2, cherry-picked

#1169 cherry-picked from 3.5
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.3, cherry-picked

#1170 cherry-picked from 3.5
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.4, cherry-picked

#1156 Add paragraph about needing privileges to create and drop indexes and constraints
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.1, THIS VERSION ONLY, cypher

#1157 Add paragraph about needing privileges to create and drop indexes and constraints
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.2, THIS VERSION ONLY, cypher

#1173 Added deprecation links for 4.3+
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.3, cherry-pick-this-forward

#1172 Deprecation link added for drop index + constraint
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.2, cherry-pick-this-to-4.0, cherry-pick-this-to-4.1

#1175 Added deprecation links for 4.4
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.4, cherry-picked

#1177 Deprecation link added for drop index + constraint
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.1, cherry-picked

#1178 Deprecation link added for drop index + constraint
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.0, cherry-picked

#1174 Add info about needed privileges for constraint commands
  cypher/cypher-docs/src/docs/dev/ql/constraints/syntax.adoc
Labels: 4.3, THIS VERSION ONLY, cypher

#1158 Described unit-subqueries.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
Labels: 4.4, cypher, team-planner

#1176 Document that unique property constraints can be composite
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/general/databases-and-graphs.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/index.adoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/syntax.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: 4.4, cypher

#1185 Allocate web containers in temporary directories instead of system directory
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
Labels: cherry-pick-this-to-4.3

#1186 Allocate web containers in temporary directories instead of system directory
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
Labels: 4.3, cherry-picked

#1184 Minimum length of var length patterns when length omitted
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
Labels: 4.4, cherry-pick-this-to-4.3, cypher, team-planner

#1183 Add note that USING PERIODIC COMMIT does not work with SSR
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.4, cypher, team-planner

#1187 Wait for the indexes after creating them
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.0, cherry-pick-this-forward, cypher

#1188 4.3 variable length pattern
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
Labels: 4.3, cherry-picked

#1190 Allocate web containers in temporary directories instead of system directory
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
Labels: 4.1, cherry-picked

#1191 Wait for the indexes after creating them
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.2, cherry-picked

#1189 Allocate web containers in temporary directories instead of system directory
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
Labels: 4.2, cherry-picked

#1192 Wait for the indexes after creating them
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.3, cherry-pick-this-forward, cherry-picked

#1180 Add a link so examples how to construct timezones can be found easier.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.4, cypher, team-planner

#1179 Improve concurrent merge behavior documentation.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MergeTest.scala
Labels: 4.4, cherry-pick-this-to-4.3, cypher, team-planner

#1194 Improve concurrent merge behavior documentation.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MergeTest.scala
Labels: 4.3, cherry-picked

#1181 Add reference to IS NULL operator from "Working with null" section
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/working-with-null.asciidoc
Labels: 4.4, cypher, team-planner

#1182 Add sections on variable introduction and wildcard to WITH
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.4, cypher, team-planner

#1195 Cleanup unused renamed imports from tests
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/ExtensionTestingDocIT.java
  neo4j-harness-test/src/test/java/org/neo4j/harness/doc/JUnitDocIT.java
Labels: 4.4

#1196 Remove example block delimeter from end of file
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 4.3, cherry-pick-this-to-4.0, cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick-this-to-4.4

#1200 Remove example block delimiter from end of file (#1196)
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 4.2, cherry-picked

#1199 Remove example block delimiter from end of file (#1196)
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 4.1, cherry-picked

#1201 Remove example block line from end of file (#1196)
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 4.4, cherry-picked

#1198 Remove example block delimiter from end of file (#1196)
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 4.0, cherry-picked

#1203 4.4 cleanup temporary test folders and files after building
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/IntroDocTest.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/captureStateAsGraphVizTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerTestUtils.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 4.4, bug, cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick-this-to-4.3, enhancement

#1208 removed redundant test that was generateing empty tmp folders
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/captureStateAsGraphVizTest.scala
Labels: 4.1, bug, cherry-pick-this-to-4.0, enhancement

#1206 4.4 cleanup temporary test folders and files after building (#1203)
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/IntroDocTest.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/captureStateAsGraphVizTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerTestUtils.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 4.3, cherry-picked

#1207 4.4 cleanup temporary test folders and files after building (#1203)
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/IntroDocTest.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/captureStateAsGraphVizTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerTestUtils.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 4.2, cherry-picked

#1209 removed redundant test that was generateing empty tmp folders (#1208)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/tests/captureStateAsGraphVizTest.scala
Labels: 4.0, cherry-picked

#1210 Remove introduction header on Database Management section
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.3, cherry-pick-this-forward

#1213 remove persistent webcontainer
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/WebContainerHelper.java
Labels: 4.2, cherry-pick-this-forward

#1214 remove persistent webcontainer (#1213)
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/WebContainerHelper.java
Labels: 4.3, cherry-picked

#1215 remove persistent webcontainer (#1213)
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/WebContainerHelper.java
Labels: 4.4, cherry-picked

#1212 4.1 cleanup temporary test folders and files after building
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/IntroDocTest.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerHolder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/WebContainerTestUtils.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/WebContainerHelper.java
Labels: 4.1, bug, enhancement

#1211 Remove introduction header on Database Management section
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.4, cherry-picked

#1217 removes temporary folder
  server-test-utils/src/main/java/org/neo4j/doc/server/ServerTestUtils.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityServerBuilder.java
Labels: 4.0, bug, enhancement

#1219 Removed broken link
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: 4.3, cherry-pick-this-forward, cypher

#1220 Removed broken link
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: 4.4, cherry-picked

#1221 Add includes for the restructuring
  cypher/cypher-docs/src/docs/dev/index.asciidoc
Labels: 4.3, cherry-pick-this-forward

#1222 Add includes for the restructuring (#1221)
  cypher/cypher-docs/src/docs/dev/index.asciidoc
Labels: 4.4, cherry-picked
