Repository neo4j/neo4j-documentation, pull requests merged in 2021-09, with the labels that each got.

#1240 Fix wrong link for privileges to show role privileges
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
Labels: cypher, 4.2, cherry-picked

#1237 4.3 neo4j implementation leap seconds
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: enhancement, 4.3, cherry-pick-this-to-4.4

#1231 Add some node pattern predicates examples
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: cypher, team-cypher-planner, 4.4

#1241 4.3 neo4j implementation leap seconds (#1237)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: cherry-picked, 4.4

#1242 fix second range specification
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: bug, 3.5, cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick-this-to-4.0

#1245 fix second range specification (#1242)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.2, cherry-picked

#1243 fix second range specification (#1242)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.0, cherry-picked

#1244 fix second range specification (#1242)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.1, cherry-picked

#1246 remove empty lines from settings list output
  doctools/src/main/java/org/neo4j/doc/AsciiDocListGenerator.java
Labels: 4.3, cherry-pick-this-forward

#1238 Update constraint syntax
  cypher/cypher-docs/src/docs/dev/advanced-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/examples.adoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/syntax.adoc
  cypher/cypher-docs/src/docs/graphgists/import/import-csv-with-cypher.asciidoc
  cypher/cypher-docs/src/docs/graphgists/intro/labels.adoc
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/export/SubGraphExporter.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MergeTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  neo4j-harness-enterprise-test/src/test/java/org/neo4j/harness/enterprise/doc/JUnitDocIT.java
Labels: cypher, 4.4

#1239 Document additional columns for SHOW DATABASES
  cypher/cypher-docs/src/docs/dev/ql/administration/show-databases-columns.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: cypher, 4.4

#1248 remove dead code
  cypher/cypher-docs/pom.xml
  cypher/graphgist/README.asciidoc
  cypher/graphgist/pom.xml
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/Block.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/BlockType.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/CypherDoc.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/Main.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/OutputHelper.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/Result.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/ResultWalker.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/State.java
  cypher/graphgist/src/main/java/org/neo4j/doc/cypherdoc/TestFailureException.java
  cypher/graphgist/src/test/java/org/neo4j/doc/cypherdoc/BlockTypeTest.java
  cypher/graphgist/src/test/java/org/neo4j/doc/cypherdoc/CypherDocTest.java
  cypher/graphgist/src/test/resources/failing-query.asciidoc
  cypher/graphgist/src/test/resources/hello-world.asciidoc
  cypher/graphgist/src/test/resources/patterns-in-practice.adoc
  cypher/graphgist/src/test/resources/profiling-test.asciidoc
  cypher/graphgist/src/test/resources/tests-with-sql.asciidoc
  cypher/pom.xml
Labels: enhancement, 4.4

#1249 Updated the id function example
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, 4.3, cherry-pick-this-to-4.4, cherry-pick-this-to-4.0, cherry-pick-this-to-3.5

#1250 4.4 id function description
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: cherry-picked, 4.4

#1251 4.2 id function
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.2, cherry-picked

#1252 4.1 id function
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.1, cherry-picked

#1253 4.0 id function
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.0, cherry-picked

#1254 Updated the id function description
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 3.5, cherry-picked

#1255 Document options clause for remaning indexes and constraints
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/syntax.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: cypher, 4.4

#1256 Btree indexes are deprecated
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cypher, 4.4

#1228 Generate internal settings documentation
  config-docs/pom.xml
  config-docs/src/main/java/org/neo4j/doc/ConfigDocsTool.java
Labels: cherry-picked, THIS VERSION ONLY, 4.3

#1261 Update version to 4.3.5-SNAPSHOT
  config-docs/pom.xml
  cypher/cypher-docs/pom.xml
  cypher/cypher-prettifier/pom.xml
  cypher/graphgist/pom.xml
  cypher/pom.xml
  cypher/refcard-tests/pom.xml
  doctools/pom.xml
  embedded-examples/pom.xml
  functions/pom.xml
  graphviz/pom.xml
  import-tool/pom.xml
  jmx/pom.xml
  kernel/pom.xml
  metrics-docs/pom.xml
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-test/pom.xml
  pom.xml
  procedures/pom.xml
  server-docs/pom.xml
  server-examples/pom.xml
  server-test-utils/pom.xml
  test-framework/pom.xml
Labels: 4.3

#1260 Add examples for failing to create already existing indexes and constraints
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/examples.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  graphviz/src/main/java/org/neo4j/visualization/asciidoc/AsciidocHelper.java
Labels: cypher, 4.4

#1262 copied section from 4.3 for wait/nowait
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.2
