Repository neo4j/neo4j-documentation, pull requests merged in 2021-11, with the labels that each got.

#1297 Fix query statistics assertion
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/QueryStatisticsTestSupport.scala
Labels: team-cypher-planner, 4.4

#1293 Aggregation with implicit grouping keys are deprecated
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cypher, 4.4, cherry-pick-this-to-4.4

#1299 Aggregation with implicit grouping keys are deprecated
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cypher, 4.4

#1300 Add MultiNodeIndexSeek to execution plans operator summary
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
Labels: cypher, cherry-pick-this-to-4.4, 5.0

#1301 Add MultinodeIndexSeek to execution plans operator summary
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
Labels: cherry-picked, 4.4

#1303 Clarify that the password is a string and not a plain token as the username
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-alter-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-create-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
Labels: cypher, 4.2, cherry-pick-this-to-4.1, cherry-pick-this-to-4.0

#1304 Clarify that the password is a string (#1303)
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-alter-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-create-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
Labels: 4.1, cherry-picked

#1305 Clarify that the password is a string (#1303)
  cypher/cypher-docs/src/docs/dev/ql/administration/security/security-and-indexes-intro.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-alter-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax-create-user.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
Labels: 4.0, cherry-picked

#1302 JDK 17 adaptations
  embedded-examples/src/main/java/org/neo4j/examples/socnet/FriendsStatusUpdateIterator.java
  embedded-examples/src/main/java/org/neo4j/examples/socnet/Person.java
  embedded-examples/src/main/java/org/neo4j/examples/socnet/PersonRepository.java
  embedded-examples/src/main/java/org/neo4j/examples/socnet/StatusUpdate.java
  embedded-examples/src/test/java/org/neo4j/examples/Neo4jBasicDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/ProcedureExampleDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/socnet/SocnetTest.java
  functions/pom.xml
  import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java
  pom.xml
  procedures/pom.xml
Labels: 5.0

#1313 Pagecache mem setting is a long
  embedded-examples/src/test/java/org/neo4j/examples/Neo4jBasicDocTest.java
  embedded-examples/src/test/java/org/neo4j/examples/StartWithConfigurationDocTest.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 5.0

#1310 Add optional S to grant/revoke roles syntax summary
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
Labels: cypher, 4.2, cherry-pick-this-to-4.1, cherry-pick-this-to-4.0

#1316 added optional s to grant and revoke commands
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
Labels: 4.0, cherry-picked

#1317 Add optional S to grant/revoke roles syntax summary (#1310)
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
Labels: 4.1, cherry-picked

#1311 Update CREATE FULLTEXT syntax summary to follow the rules we set up for such summaries
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-full-text-search/create-fulltext-syntax.asciidoc
Labels: cypher, 4.3, cherry-pick-this-forward

#1319 updated syntax
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-full-text-search/create-fulltext-syntax.asciidoc
Labels: cherry-picked, 4.4

#1315 Update default privileges for PUBLIC role
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
Labels: cypher, 4.2, THIS VERSION ONLY

#1318 Change Markdown to AsciiDoc code environments.
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.3, team-cypher-planner, 4.4, 5.0

#1323 Change Markdown to AsciiDoc code environments
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: cherry-picked, 4.4

#1324 Bump jackson-databind from 2.9.10.7 to 2.9.10.8
  pom.xml
Labels: 5.0

#1321 coverted long value to needed string value
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 5.0

#1322 Change Markdown to AsciiDoc code environments
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: cherry-picked, 4.3

#1314 Do not assert on order of results.
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: team-cypher-planner, 5.0
