Repository neo4j/neo4j-documentation, pull requests merged in 2021-03, with the labels that each got.

#962 4.0 cypher query syntax fix part 9
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnwindTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.0, cherry-pick-this-forward

#969 4.0 cypher query syntax fix part 9 (#962)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnwindTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.1, cherry-picked

#970 4.0 cypher query syntax fix part 9 (#962)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnwindTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.2, cherry-picked

#971 4.0 cypher query syntax fix part 9 (#962)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnwindTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.3, cherry-picked

#922 Document YIELD and WHERE for SHOW INDEXES
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
Labels: 4.3, cypher

#963 SHOW USER/ROLE PRIVILEGES allows yield and where
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
Labels: 4.1, THIS VERSION ONLY, cypher

#964 `SHOW ... WHERE ... RETURN ...` without the `YIELD` is not allowed
  cypher/cypher-docs/src/docs/dev/ql/administration/databases-command-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-all-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.2, THIS VERSION ONLY, cypher

#965 `SHOW ... WHERE ... RETURN ...` without the `YIELD` is not allowed
  cypher/cypher-docs/src/docs/dev/ql/administration/databases-command-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/role-management-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-all-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-role-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/show-user-privileges-syntax.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/user-management-syntax.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
Labels: 4.3, cherry-picked, cypher

#972 style for where clause
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.0, cherry-pick-this-forward

#974 style for where clause (#972)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.2, cherry-picked

#975 style for where clause (#972)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.3, cherry-picked

#973 style for where clause (#972)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.1, cherry-picked

#976 4.0 cypher query syntax fix part 11
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LimitTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SkipTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.0, cherry-pick-this-forward

#977 Upgrade to 4.1.8-SNAPSHOT
  config-docs/pom.xml
  cypher/cypher-docs/pom.xml
  cypher/cypher-prettifier/pom.xml
  cypher/graphgist/pom.xml
  cypher/pom.xml
  cypher/refcard-tests/pom.xml
  doctools/pom.xml
  embedded-examples/pom.xml
  graphviz/pom.xml
  import-tool/pom.xml
  jmx/pom.xml
  kernel/pom.xml
  metrics-docs/pom.xml
  neo4j-harness-enterprise-test/pom.xml
  neo4j-harness-test/pom.xml
  pom.xml
  procedures/pom.xml
  server-docs/pom.xml
  server-examples/pom.xml
  server-test-utils/pom.xml
  test-framework/pom.xml
Labels: 4.1, THIS VERSION ONLY

#978 4.1 cypher query syntax fix part 11 (#976)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LimitTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SkipTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.1, cherry-picked

#980 4.1 cypher query syntax fix part 11 (#976) (#978)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LimitTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SkipTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.2, cherry-picked

#981 4.1 cypher query syntax fix part 11 (#976) (#978)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LimitTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SkipTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.3, cherry-picked

#979 fixed cypher style for create clause
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CreateTest.scala
Labels: 4.0, cherry-pick-this-forward

#984 fixed cypher style for create clause (#979)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CreateTest.scala
Labels: 4.3, cherry-picked

#985 4.0 cypher query syntax fix part 13
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DeleteTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SetTest.scala
Labels: 4.0, cherry-pick-this-forward

#987 4.0 cypher query syntax fix part 13 (#985)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DeleteTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SetTest.scala
Labels: 4.1, cherry-picked

#989 4.0 cypher query syntax fix part 13 (#985)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DeleteTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SetTest.scala
Labels: 4.3, cherry-picked

#982 fixed cypher style for create clause (#979)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CreateTest.scala
Labels: 4.1, cherry-picked

#983 fixed cypher style for create clause (#979)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CreateTest.scala
Labels: 4.2, cherry-picked

#988 4.0 cypher query syntax fix part 13 (#985)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DeleteTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SetTest.scala
Labels: 4.2, cherry-picked

#986 4.0 cypher query syntax fix part 14
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ForeachTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/RemoveTest.scala
Labels: 4.0, cherry-pick-this-forward

#991 4.0 cypher query syntax fix part 14 (#986)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ForeachTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/RemoveTest.scala
Labels: 4.1, cherry-picked

#992 4.0 cypher query syntax fix part 14 (#986)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ForeachTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/RemoveTest.scala
Labels: 4.2, cherry-picked

#993 4.0 cypher query syntax fix part 14 (#986)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ForeachTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/RemoveTest.scala
Labels: 4.3, cherry-picked

#990 fix for merge clause
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MergeTest.scala
Labels: 4.0, cherry-pick-this-forward

#995 fix for merge clause (#990)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MergeTest.scala
Labels: 4.1, cherry-picked

#996 fix for merge clause (#990)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MergeTest.scala
Labels: 4.2, cherry-picked

#997 fix for merge clause (#990)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/MergeTest.scala
Labels: 4.3, cherry-picked

#998 4.0 cypher query syntax fix part 16
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnionTest.scala
Labels: 4.0, cherry-picked

#994 added admonition about restrictions to SHOW DBs
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.0, cherry-pick-this-forward, work in progress

#1000 4.0 cypher query syntax fix part 16 (#998)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnionTest.scala
Labels: 4.1, cherry-picked

#1003 4.1-cherry-pick-994 (#994)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.1, cherry-picked

#1005 4.2-cherry-pick-994
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.3, cherry-picked

#1004 4.2-cherry-pick-994
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.2, cherry-picked

#1001 4.0 cypher query syntax fix part 16 (#998) (#1000)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnionTest.scala
Labels: 4.2, cherry-picked

#1002 4.0 cypher query syntax fix part 16 (#998) (#1000)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UnionTest.scala
Labels: 4.3, cherry-picked

#1006 fixed cypher syntax
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
Labels: 4.1

#1007 removed link for timestamp
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.0, cherry-pick-this-forward

#999 4.0 cypher query syntax fix part 17
  cypher/cypher-docs/src/docs/dev/ql/load-csv/csv-file-format.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.0, cherry-pick-this-forward

#1012 4.0 cypher query syntax fix part 17 (#999)
  cypher/cypher-docs/src/docs/dev/ql/load-csv/csv-file-format.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.2, cherry-picked

#1013 4.0 cypher query syntax fix part 17 (#999)
  cypher/cypher-docs/src/docs/dev/ql/load-csv/csv-file-format.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.3, cherry-picked

#1008 removed link for timestamp (#1007)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.1, cherry-picked

#1009 removed link for timestamp (#1007)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.2, cherry-picked

#1011 4.0 cypher query syntax fix part 17 (#999)
  cypher/cypher-docs/src/docs/dev/ql/load-csv/csv-file-format.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.1, cherry-picked

#1010 removed link for timestamp (#1007)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalTest.scala
Labels: 4.3, cherry-picked

#1017 fixed link text
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.0, cherry-pick-this-forward

#1018 fixed link text (#1017)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.1, cherry-picked

#1019 fixed link text (#1017) (#1018)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.2, cherry-picked

#1023 fixed the footer info of query result
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/QueryResultContentBuilder.scala
Labels: 4.0, cherry-pick-this-forward

#1016 Updated the cypher query functions predicates page
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
Labels: 4.0, cherry-pick-this-forward

#1020 fixed link text (#1017) (#1018)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: 4.3, cherry-picked

#1027 Updated the cypher query functions predicates page (#1016)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
Labels: 4.1, cherry-picked

#1028 Updated the cypher query functions predicates page (#1016)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
Labels: 4.2, cherry-picked

#1024 fixed the footer info of query result (#1023)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/QueryResultContentBuilder.scala
Labels: 4.1, cherry-picked

#1025 fixed the footer info of query result (#1023)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/QueryResultContentBuilder.scala
Labels: 4.2, cherry-picked

#1026 fixed the footer info of query result (#1023)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/QueryResultContentBuilder.scala
Labels: 4.3, cherry-picked

#1014 Ordering of different types
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
Labels: 4.3, cypher

#1029 Updated the cypher query functions predicates page (#1016)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
Labels: 4.3, cherry-picked

#1031 made the introduction page about paths in cypher static
  cypher/cypher-docs/src/docs/dev/general/cypher-path-matching.asciidoc
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
Labels: 4.0, cherry-pick-this-forward

#1032 made the introduction page about paths in cypher static (#1031)
  cypher/cypher-docs/src/docs/dev/general/cypher-path-matching.asciidoc
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
Labels: 4.1, cherry-picked

#1022 4.0 cypher query syntax fix part 19
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.0, cherry-pick-this-forward

#1033 made the introduction page about paths in cypher static (#1031)
  cypher/cypher-docs/src/docs/dev/general/cypher-path-matching.asciidoc
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
Labels: 4.2, cherry-picked

#1034 made the introduction page about paths in cypher static (#1031)
  cypher/cypher-docs/src/docs/dev/general/cypher-path-matching.asciidoc
  cypher/cypher-docs/src/docs/dev/general/index.asciidoc
Labels: 4.3, cherry-picked

#888 Updated read-only example
  embedded-examples/src/test/java/org/neo4j/examples/ReadOnlyDocTest.java
Labels: 4.3

#1035 4.0 cypher query syntax fix part 19 (#1022)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.1, cherry-picked

#1037 4.3 cherry pick 1022
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.3, cherry-picked

#1036 4.0 cypher query syntax fix part 19 (#1022)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 4.2, cherry-picked

#1039 update include link in administration index
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.0, cherry-pick-this-forward

#1040 update include link in administration index (#1039)
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.1, cherry-picked

#1042 update include link in administration index (#1039)
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.3, cherry-picked

#1043 Fix broken links reported by xrefs check
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.0, cherry-pick-this-forward

#1046 fix link to full text search (#1043)
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.1, cherry-picked

#1047 fix link to full text search (#1043)
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.2, cherry-picked

#1045 fixed xref comma text issue
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 3.5, bug

#1030 4.0 cypher query syntax fix part 20
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
Labels: 4.0, cherry-pick-this-forward

#1044 fixed rendering issue that comma was now shown for xrefs
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.0, bug, cherry-pick-this-forward

#1048 4.0 cypher query syntax fix part 20 (#1030)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
Labels: 4.1, cherry-picked

#1049 4.0 cypher query syntax fix part 20 (#1030)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
Labels: 4.2, cherry-picked

#1050 4.0 cypher query syntax fix part 20 (#1030)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
Labels: 4.3, cherry-picked

#1051 4.1 cherry pick 1044
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.1, cherry-picked

#1053 fixed rendering issue that comma was now shown for xrefs (#1044)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.3, cherry-picked

#1052 fixed rendering issue that comma was now shown for xrefs (#1044)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.2, cherry-picked

#1055 moved static content of query-call-subquery-correlated.adoc
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
  cypher/cypher-docs/src/docs/dev/query-call-subquery-correlated.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
Labels: 4.0, THIS VERSION ONLY, bug

#1057 fix link to full text search (#1043)
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
Labels: 4.3, cherry-picked

#1058 Replace Ceasar with Caesar in example
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentationTestBaseTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 3.5, bug, cherry-pick-this-forward

#1059 Fix typo
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
Labels: 3.5, bug, cherry-pick-this-forward

#1060 Replace Ceasar with Caesar in example
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentationTestBaseTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.0, cherry-picked

#1061 Replace Ceasar with Caesar in example
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentationTestBaseTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.1, cherry-picked

#1062 Replace Ceasar with Caesar in example
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentationTestBaseTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.2, cherry-picked

#1063 Replace Ceasar with Caesar in example
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentationTestBaseTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WithTest.scala
Labels: 4.3, cherry-picked

#1064 Fix typo
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
Labels: 4.0, cherry-picked

#1067 Fix typo
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
Labels: 4.3, cherry-picked

#1065 Fix typo
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
Labels: 4.1, cherry-picked

#1066 Fix typo
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
Labels: 4.2, cherry-picked
