Repository neo4j/neo4j-documentation, pull requests merged in 2021-06, with the labels that each got.

#1124 Await indexes to come online
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
Labels: 4.3, cypher

#1123 4.3 fix layout for version deltas page
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.3, cherry-pick-this-forward, cypher

#1125 Await indexes to come online
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/tooling/RestartableDatabase.scala
Labels: 4.4, cherry-picked, cypher

#1126 4.3 fix layout for version deltas page (#1123)
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.4, cherry-picked

#1129 fixed test
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: 4.4, bug

#1127 version 4.2 structure
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.3, cherry-pick-this-forward

#1128 Fix broken link query tuning
  cypher/cypher-docs/src/docs/dev/query-tuning-indexes.adoc
Labels: 4.3, cherry-pick-this-forward, cypher, team-planner

#1131 Fix broken link in query tuning section (#1128)
  cypher/cypher-docs/src/docs/dev/query-tuning-indexes.adoc
Labels: 4.4, cherry-picked

#1130 version 4.2 structure (#1127)
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.4, cherry-picked

#1132 Pontusmelke 4.4 relationship operators
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.4, cherry-picked

#1133 Update the compatibility section to have correct versions
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.4, cypher

#1135 4.3 fix build issues for cypher manual
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalDurationFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.3, bug, cherry-pick-this-to-4.4

#1136 4.3 fix build issues for cypher manual (#1135)
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalDurationFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TemporalFunctionsTest.scala
Labels: 4.4, bug, cherry-picked

#1134 4.3 fix includes not shown
  cypher/cypher-docs/src/docs/dev/ql/listing/listing-functions-columns.adoc
  cypher/cypher-docs/src/docs/dev/ql/listing/listing-functions-syntax.adoc
  cypher/cypher-docs/src/docs/dev/ql/listing/listing-procedures-columns.adoc
  cypher/cypher-docs/src/docs/dev/ql/listing/listing-procedures-syntax.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowProceduresTest.scala
Labels: 4.3, cherry-pick-this-forward

#1137 4.3 fix includes not shown (#1134)
  cypher/cypher-docs/src/docs/dev/ql/listing/listing-functions-columns.adoc
  cypher/cypher-docs/src/docs/dev/ql/listing/listing-functions-syntax.adoc
  cypher/cypher-docs/src/docs/dev/ql/listing/listing-procedures-columns.adoc
  cypher/cypher-docs/src/docs/dev/ql/listing/listing-procedures-syntax.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowProceduresTest.scala
Labels: 4.4, bug, cherry-picked

#1138 removed old file
  cypher/cypher-docs/src/docs/dev/ql/merge/index.asciidoc
Labels: 4.3, bug, cherry-pick-this-to-4.4

#1139 removed old file (#1138)
  cypher/cypher-docs/src/docs/dev/ql/merge/index.asciidoc
Labels: 4.4, cherry-picked

#1141 Fix the widths on the built in procedures table (3.5 only)
  procedures/src/main/java/org/neo4j/doc/ProcedureReferenceGenerator.java
Labels: 3.5, THIS VERSION ONLY, work in progress

#1143 fixed leveloffset
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.3, bug, cherry-pick-this-to-4.4

#1140 4.3 advanced query tuning example
  cypher/cypher-docs/src/docs/dev/advanced-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/dev/basic-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/actors.csv
  cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/basic-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/directors.csv
  cypher/cypher-docs/src/docs/graphgists/query-tuning/movies.csv
  cypher/cypher-docs/src/docs/graphgists/query-tuning/movies_actors.csv
Labels: 4.3, cherry-pick-this-to-4.4

#1145 4.3 advanced query tuning example (#1140)
  cypher/cypher-docs/src/docs/dev/advanced-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/dev/basic-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/actors.csv
  cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/basic-query-tuning-example.asciidoc
  cypher/cypher-docs/src/docs/graphgists/query-tuning/directors.csv
  cypher/cypher-docs/src/docs/graphgists/query-tuning/movies.csv
  cypher/cypher-docs/src/docs/graphgists/query-tuning/movies_actors.csv
Labels: 4.4, cherry-picked

#1144 fixed leveloffset (#1143)
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.4, cherry-picked

#1142 4.3 fix missing abstracts
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-db-hits.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowProceduresTest.scala
Labels: 4.3, cherry-pick-this-to-4.4

#1146 4.3 fix missing abstracts (#1142)
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-db-hits.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PatternTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowProceduresTest.scala
Labels: 4.4, cherry-picked

#1148 Don't try to generate documentation from a deleted class
  config-docs/pom.xml
Labels: 4.4, kernel

#1150 Generate internal settings documentation
  config-docs/pom.xml
  config-docs/src/main/java/org/neo4j/doc/ConfigDocsTool.java
Labels: 4.4, kernel
