Repository neo4j/neo4j-documentation, pull requests merged in 2022-08, with the labels that each got.

#1563 Update LOAD CSV remote url to https
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, 4.3, cherry-pick-this-to-4.0, cherry-pick-this-to-3.5

#1564 Update remote url to https (#1563)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.2, cherry-picked

#1561 Added deprecation documentation of shortest path and allShortestPaths
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: team-cypher-planner, 5.0

#1565 Update remote url to https (#1563)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.1, cherry-picked

#1566 Update remote url to https (#1563)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.0, cherry-picked

#1567 Update remote url to https (#1563)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 3.5, cherry-picked

#1555 Deprecate case matching on null in 4.4
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cypher, Dependencies w. other PR, THIS VERSION ONLY, 4.4

#1562 Add `store` column to `SHOW DATABASES`
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/show-databases-columns.asciidoc
Labels: cypher, 5.0

#1568 Mention special treatment CALL IN TRANSACTIONS delete
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DeleteTest.scala
Labels: team-cypher-planner

#1569 Add phrase about scoring and text arrays in fulltext index
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 5.0

#1570 Add label for all enterprise settings
  config-docs/src/main/java/org/neo4j/doc/ConfigDocsGenerator.java
  config-docs/src/main/java/org/neo4j/doc/DocsConfigValue.java
  doctools/src/main/java/org/neo4j/doc/AsciiDocListGenerator.java
  doctools/src/main/java/org/neo4j/doc/SettingDescription.java
  doctools/src/main/java/org/neo4j/doc/SettingDescriptionImpl.java
  doctools/src/main/java/org/neo4j/doc/SettingsDescription.java
  doctools/src/main/java/org/neo4j/doc/SettingsDocumenter.java
Labels: kernel, 5.0

#1572 Moving =~ from string operators to string-specific comparison
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: cypher, cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick-this-to-4.3, 4.4, cherry-pick-this-to-4.0, cherry-pick-this-to-5.0

#1574 Cherry pick of (#1572)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.3

#1575 Cherry-pick of (#1572)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.2

#1576 Cherry-pick of (#1572)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.1

#1577 Cherry pick of (#1572)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: 4.0

#1573 Fix test failures where a particular order was assumed
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
Labels: bug, cypher, 5.0

#1578 Cherry pick of (#1572)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OperatorsTest.scala
Labels: cherry-picked, 5.0

#1579 Fix CommunityWebContainer to work with new log4j logging
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 5.0

#1580 Fixes build issues
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/CypherPrettifier.scala
Labels: 5.0

#1556 Deprecate case matching on null in 4.4 and updated case for 5.0
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cypher, Dependencies w. other PR, THIS VERSION ONLY, 5.0

#1581 Add columns to SHOW DATABASES for autonomous clusters
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/show-databases-columns.asciidoc
Labels: cypher, Dependencies w. other PR, 5.0

#1586 Fixed build issues
  config-docs/src/main/java/org/neo4j/doc/ConfigDocsGenerator.java
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 5.0, fix-build
