Repository neo4j/neo4j-documentation, pull requests merged in 2022-04, with the labels that each got.

#1464 Fix build broken due to Foldable refactoring (treeExists)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: 4.2, cherry-picked, team-cypher-planner

#1466 Add section about text array handling in full text indexes
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
Labels: 5.0

#1465 Add note about deprecation of exists(prop)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: cherry-pick-this-to-4.3, 4.4, fix-build

#1467 Add note about deprecation of exists(prop) (#1465)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: cherry-picked, 4.3

#1459 Include token indexes in query tuning section
  cypher/cypher-docs/src/docs/dev/query-tuning-indexes.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DocumentingTestBase.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
Labels: team-cypher-planner, 5.0

#1452 Remove B-tree from index and constraint commands
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/examples.adoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/syntax.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: cypher, 5.0

#1469 Fix failing tests where we use no longer supported pattern expressions
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ReturnTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/PatternsTest.scala
Labels: team-cypher-planner, 5.0

#1463 Update SHOW TRANSACTIONS columns with default values
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/TransactionsCommandTest.scala
Labels: cypher, 5.0

#1476 Fixes incorrect href for profiling a query
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: 4.2, cherry-picked

#1475 Fixes incorrect href for profiling a query
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: cherry-picked, 4.3

#1474 Fixes incorrect href for profiling a query
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: cherry-picked, 5.0

#1479 Add a note about the call {} in transaction for a detach delete sets transaction size
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
Labels: team-cypher-planner, 4.4, cherry-pick-this-to-5.0

#1480 Add a note about the call {} in transaction for a detach delete sets transaction size
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
Labels: cherry-picked, 5.0

#1481 Fixes the Neo4j Cypher default version
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: 4.4, cherry-pick-this-to-5.0

#1483 Add the Neo4j Cypher default version
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: cherry-picked, 5.0

#1478 clarification of read-only db
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: cherry-pick-this-forward, 4.4

#1484 clarification of read-only db (#1478)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: cherry-picked, 5.0
