Repository neo4j/neo4j-documentation, pull requests merged in 2022-02, with the labels that each got.

#1408 4.3 remove redundant content
  cypher/cypher-docs/src/docs/dev/administration.asciidoc
  cypher/cypher-docs/src/docs/dev/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/admin-role-introduction.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/security/administration-security-administration-toc.asciidoc
Labels: 4.3, cherry-pick-this-to-4.4, cherry-pick-this-to-5.0

#1404 head, last, tail is now explicitly explained
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ListExpressionsTest.scala
Labels: 4.3, team-cypher-planner, cherry-pick-this-to-4.4, cherry-pick-this-to-5.0

#1413 head, last, tail is now explicitly explained (#1404)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ListExpressionsTest.scala
Labels: cherry-picked, 4.4

#1414 head, last, tail is now explicitly explained (#1404)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ListExpressionsTest.scala
Labels: cherry-picked, 5.0

#1415 Fixes administration structure changes done in 4.3
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/general/databases-and-graphs.asciidoc
  cypher/cypher-docs/src/docs/dev/general/querying-updating-administering.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/syntax.adoc
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowProceduresTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabaseManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabasePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DbmsPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/PrivilegeManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/RoleManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementPrivilegeTest.scala
Labels: 4.4, cherry-pick-this-to-5.0

#1417 Fixes administration structure changes done in 4.3 (#1415)
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/general/databases-and-graphs.asciidoc
  cypher/cypher-docs/src/docs/dev/general/querying-updating-administering.asciidoc
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/syntax.adoc
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowProceduresTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabaseManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DatabasePrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/DbmsPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/PrivilegeManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/RoleManagementPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementPrivilegeTest.scala
Labels: cherry-picked, 5.0

#1421 access-control links fix
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/general/databases-and-graphs.asciidoc
Labels: 4.3, cherry-pick-this-to-4.4, cherry-pick-this-to-5.0

#1423 access-control links fix (#1421)
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/general/databases-and-graphs.asciidoc
Labels: cherry-picked, 4.4

#1424 access-control links fix (#1421)
  cypher/cypher-docs/src/docs/dev/clause.asciidoc
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/general/databases-and-graphs.asciidoc
Labels: cherry-picked, 5.0

#1425 Improvements to call { } in transactions (#1422)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
Labels: cherry-picked, 5.0

#1419 Adds an example of how to use CASE WHEN as part of WITH
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
Labels: cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick-this-to-4.3, cherry-pick-this-to-4.4, cherry-pick-this-to-4.0, cherry-pick-this-to-3.5, 5.0

#1428 Adds an example of how to use CASE WHEN as part of WITH (#1419)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
Labels: 4.2, cherry-picked

#1430 Adds an example of how to use CASE WHEN as part of WITH (#1419)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
Labels: 4.0, cherry-picked

#1426 Adds an example of how to use CASE WHEN as part of WITH (#1419)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
Labels: cherry-picked, 4.4

#1427 Adds an example of how to use CASE WHEN as part of WITH (#1419)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
Labels: cherry-picked, 4.3

#1431 Adds an example of how to use CASE WHEN as part of WITH (#1419)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
Labels: 3.5, cherry-picked

#1416 Make it clearer that the "greedy" option can drastically reduce planning time
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: 4.2, cherry-pick-this-forward

#1432 Make it clearer that the "greedy" option can drastically reduce planning time
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: cherry-picked, 4.3, cherry-pick-this-to-4.4, cherry-pick-this-to-5.0

#1433 Make it clearer that the "greedy" option can drastically reduce planning time
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: cherry-picked, 4.4

#1420 removed `ON DEFAULT` for privileges
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cypher, 5.0

#1434 Make it clearer that the "greedy" option can drastically reduce planning time
  cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
Labels: cherry-picked, 5.0

#1435 Adapt to product log changes
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/TestEnterpriseDatabaseManagementServiceBuilder.java
  server-test-utils/src/main/java/org/neo4j/doc/server/helpers/CommunityWebContainerBuilder.java
Labels: 5.0

#1438 fix build error
  pom.xml
Labels: 5.0, breaking change

#1436 Use the Neo4j Prettifier instead of a custom one.
  cypher/cypher-docs/src/test/java/org/neo4j/cypher/example/JavaExecutionEngineDocTest.java
  cypher/cypher-prettifier/pom.xml
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/CypherPrettifier.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/Prettifier.scala
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/ParserTestBase.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
  cypher/pom.xml
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/RefcardTest.scala
  embedded-examples/src/test/java/org/neo4j/examples/AbstractJavaDocTestBase.java
Labels: cypher, Dependencies w. other PR, 5.0

#1328 Add a 5.0 section to deprecations, additions and removals chapter
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cypher, 5.0

#1440 fix link constraints refcard
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
Labels: 4.3, cherry-pick-this-to-4.4, cherry-pick-this-to-5.0

#1442 fix link constraints refcard (#1440)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
Labels: cherry-picked, 4.4

#1443 fix link constraints refcard (#1440)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ConstraintTest.scala
Labels: cherry-picked, 5.0

#1439 Remove deprecated create index and constraint commands
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/constraints/examples.adoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
Labels: cypher, 5.0

#1441 replace deprecated dbms.procedures() with SHOW PROCEDURES
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: cypher, 5.0
