Repository neo4j/neo4j-documentation, pull requests merged in 2022-11, with the labels that each got.

#1659 Add back in cypher-prettifier module to fix build
  cypher/cypher-prettifier/pom.xml
  cypher/pom.xml
  pom.xml
Labels: fix-build, 5.2

#1664 fixing deprecated label formatting
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: 5.0, cherry-pick-this-to-5.1

#1665 5.1 cherry-pick of 1664
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ScalarFunctionsTest.scala
Labels: cherry-picked, 5.1

#1666 use longer password than 7 characters in test
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowFunctionsTest.scala
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ShowProceduresTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/ListPrivilegeTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/RoleManagementTest.scala
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/UserManagementTest.scala
  server-docs/src/test/java/org/neo4j/doc/server/rest/security/AuthenticationDocIT.java
Labels: cypher

#1625 Add deprecation for duplicated variable length relationships.
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cypher, Dependencies w. other PR, THIS VERSION ONLY, 5.2

#1661 Removed superfluous parenthesis
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
Labels: cherry-pick-this-forward, team-cypher-planner, static

#1669 Removed superfluous parenthesis (#1661)
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
Labels: cherry-picked, static

#1670 Catch up the 5.1 and 5.2 deprecations
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cherry-picked, 5.2
