Repository neo4j/neo4j-documentation, pull requests merged in 2022-01, with the labels that each got.

#1346 Added a note about periodic commit
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: 4.4, cherry-pick-this-to-5.0

#1345 Improve the structure of the deprecations page in the Cypher Manual
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.3, cherry-pick-this-forward

#1348 Improve the structure of the deprecations page + 4.4 group deprecations
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cherry-picked, 4.4

#1351 4.1 group deprecations
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.1, cherry-picked

#1344 Improved the wording of the wait options
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: 4.3, cherry-pick-this-forward

#1356 Improved the wording of the wait options
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: cherry-picked, 4.4, cherry-pick-this-to-5.0

#1353 Update Deprecations page
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.4

#1354 Grouped the Deprecations, additions, etc. page
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.0, cherry-picked

#1355 Grouped the Deprecations, additions, etc. page
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 3.5, cherry-picked

#1350 Improve the structure of the deprecations page
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: 4.2, cherry-picked

#1359 linenumber() when your CSV has headers
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
Labels: cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick-this-to-4.3, 4.4, cherry-pick-this-to-4.0, cherry-pick-this-to-5.0

#1362 linenumber() when your CSV has headers
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
Labels: 4.2, cherry-picked

#1361 linenumber() when your CSV has headers
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
Labels: cherry-picked, 4.3

#1363 linenumber() when your CSV has headers
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
Labels: 4.1, cherry-picked

#1364 linenumber() when your CSV has headers
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
Labels: 4.0, cherry-picked

#1347 Add info about globbing and escaping with backticks
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityAdministrationTest.scala
Labels: cypher, 4.2, THIS VERSION ONLY

#1367 Refers operators from Indexes for search performance
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: cherry-pick-this-to-4.3, 4.4, cherry-pick-this-to-5.0

#1372 Refers operators from Indexes for search performance
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.0, cherry-picked

#1371 Refers operators from Indexes for search performance
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.1, cherry-picked

#1370 Refers operators from Indexes for search performance
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: 4.2, cherry-picked

#1369 Refers operators from Indexes for search performance
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: cherry-picked, 4.3

#1368 Refers operators from Indexes for search performance
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
Labels: cherry-picked, 5.0

#1360 linenumber() when your CSV has headers
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVFunctionsTest.scala
Labels: cherry-picked, 5.0

#1357 Improved the wording of the wait options
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
Labels: cherry-picked, 5.0

#1349 Added a note about periodic commit
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/LoadCSVTest.scala
Labels: cherry-picked, 5.0

#1366 The file name for load csv needs to be url encoded if it contains spaces
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: cherry-pick-this-to-4.1, cherry-pick-this-to-4.2, cherry-pick-this-to-4.3, team-cypher-planner, 4.4, cherry-pick-this-to-4.0, cherry-pick-this-to-3.5, cherry-pick-this-to-5.0

#1373 Fixes a broken link formatting and anchor
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
Labels: bug, 3.5, THIS VERSION ONLY

#1340 Remove BRIEF/VERBOSE keywords for SHOW INDEXES/CONSTRAINTS and EXISTS keyword for SHOW CONSTRAINTS
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-prettifier/src/main/scala/org/neo4j/cypher/docgen/tooling/PrettifierParser.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierParserTest.scala
  cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
Labels: cypher, 5.0

#1320 updated syntax (#1319)
  cypher/cypher-docs/src/docs/dev/glossary.asciidoc
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-full-text-search/create-fulltext-syntax.asciidoc
Labels: cherry-picked, 5.0

#1338 fix link to user-defined procedures (#1332)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
Labels: cherry-picked, 5.0

#1352 4.4 execution plan summary
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
Labels: team-cypher-planner, 4.4, cherry-pick-this-to-5.0

#1358 4.0 order by
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: 4.0, cherry-pick-this-forward

#1382 3.5 load csv url encoding
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 3.5, cherry-picked

#1381 4.0 load csv url encoding
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 4.0, cherry-picked

#1380 load csv url encoding
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 4.1, cherry-picked

#1379 4.2 load csv url encoding
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: 4.2, cherry-picked

#1378 4.3 load csv url encoding
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: cherry-picked, 4.3

#1377 The file name for load csv needs to be url encoded if it contains spaces
  cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc
Labels: cherry-picked, 5.0

#1374 Improve the structure of the deprecations page
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
Labels: cherry-picked, 5.0

#1306 Explain semantics of subqueries
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
Labels: team-cypher-planner, 5.0

#1383 Cherry-picked 1358
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: 4.1, cherry-picked

#1384 Cherry-picked 1358
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: 4.2, cherry-picked

#1385 Cherry-picked 1358
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: cherry-picked, 4.3

#1387 Cherry-picked 1358 (#1385)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: cherry-picked, 5.0

#1386 Cherry-picked 1358 (#1385)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: cherry-picked, 4.4

#1389 Added a note about chain comparisons
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
Labels: 4.2, cherry-pick-this-forward

#1393 Added a note about chain comparisons
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
Labels: cherry-picked, 5.0

#1392 Added a note about chain comparisons
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
Labels: cherry-picked, 4.4

#1391 Added a note about chain comparisons
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
Labels: cherry-picked, 4.3

#1390 4.3 pattern comprehension explained
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListsTest.scala
Labels: cypher, 4.3, cherry-pick-this-forward, team-cypher-planner

#1395 4.3 pattern comprehension explained (#1390)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListsTest.scala
Labels: cherry-picked, 4.4

#1396 4.3 pattern comprehension explained (#1390)
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListsTest.scala
Labels: cherry-picked, 5.0

#1388 4.3 cypher planner operators page
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: 4.3, team-cypher-planner, cherry-pick-this-to-4.4, cherry-pick-this-to-5.0

#1397 4.3 cypher planner operators page (#1388)
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: cherry-picked, 4.4

#1398 4.3 cypher planner operators page (#1388)
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
  cypher/cypher-docs/src/docs/dev/execution-plans-operator-summary.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/QueryPlanTest.scala
Labels: cherry-picked, 5.0

#1394 4.3 fix link build warnings
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: 4.3, cherry-pick-this-to-4.4, cherry-pick-this-to-5.0

#1399 4.3 fix link build warnings (#1394)
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: cherry-picked, 4.4

#1400 4.3 fix link build warnings (#1394)
  cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/index.asciidoc
  cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/OrderByTest.scala
Labels: cherry-picked, 5.0

#1326 document that cypher now supports underscores in number literals.
  cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
  cypher/cypher-docs/src/docs/dev/syntax/expressions.asciidoc
Labels: cypher, 5.0

#1401 Added comments for planner operators
  cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
Labels: 4.4, cherry-pick-this-to-5.0

#1403 Fixed a broken link
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: bug, 4.3, cherry-pick-this-to-4.4, cherry-pick-this-to-5.0

#1405 Fixed a broken link (#1403)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: cherry-picked, 4.4

#1406 Fixed a broken link (#1403)
  cypher/refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard/IndexTest.scala
Labels: cherry-picked, 5.0
